### ISSUE TITLE
Trying to launch Elden Ring

### ISSUE THREAD

**Issue by Pednick** [Open-Wine-Components/ULWGL#105]
I've downloaded Elden Ring with steamcmd, but when I try to launch with:

GAMEID=umu-eldenring PROTONPATH=GE-Proton umu-run /home/user/Game/start_protected_game.exe

It doesn't start.

**Comment by R1kaB3rN** [comment]
I don't have that game, but do you know if it's a game that requires to be executed within its own directory? See https://github.com/Open-Wine-Components/umu-launcher/issues/63 for more details.

Also, more information would be helpful so please provide a traceback of the error or pasting the console output by setting `UMU_LOG=debug`.

**Comment by Pednick** [comment]
> I don't have that game, but do you know if it's a game that requires to be executed within its own directory? See #63 for more details.
> 
> Also, more information would be helpful so please provide a traceback of the error or pasting the console output by setting `UMU_LOG=debug`.

Yes it requires to be executed within its own directory. I executed through the terminal and there was nothing showing after exection and did a search for UMU_LOG=debug and came up with empty.

I tried launching through steamcmd with:

app_run 1245620

and the result was:

Game process removed: AppID 1245620 "/home/user/.local/share/Steam/steamcmd/linux32/reaper SteamLaunch AppId=1245620 -- /home/user/.local/share/Steam/steamcmd/linux32/steam-launch-wrapper -- '/home/user/Game/start_protected_game.exe'", ProcID 28687

That didn't start the game either so I tried that line in the quotes with umu and it said file missing, I think the file missing is reaper because it wasn't under that folder when I checked.

**Comment by loathingKernel** [comment]
`steamcmd` cannot launch proton games. It cannot launch most games since it lacks Steam's DRM. It is for downloading and launching game servers.

Furthermore, Proton when launched through umu does not launch proton's `steam.exe`, so the game cannot integrate with Steam for DRM or online features.

Just use the Steam client to launch the game since you have it on Steam.

**Comment by Pednick** [comment]
> `steamcmd` cannot launch proton games. It cannot launch any games since it lacks Steam's DRM. It is for downloading and launching game servers.
> 
> Furthermore, Proton when launched through umu does not launch proton's `steam.exe`, so the game cannot integrate with Steam for DRM or online features.
> 
> Just use Steam to launch the game since you have it on Steam.

Well yeah, I know that but my whole point is that I wanted to play the game through umu which is the whole point of running games without steam. I would like to know if umu can run steam bought games and prefer umu over steam.

**Comment by Pednick** [comment]
Forget about this, I'm closing this.
