### ISSUE TITLE
Heroic Games Launcher support

### ISSUE THREAD

**Issue by esanscoopsers** [Open-Wine-Components/ULWGL#108]
I posted a feature request for support for umu launcher in heroic on the heroic github https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3801

I assume this would require some collaboration

**Comment by mirkobrombin** [comment]
Heroic’s team is involved in the project already

**Comment by R1kaB3rN** [comment]
Heroic Games Launcher support is already planned. To track the progress, see https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3724
