### ISSUE TITLE
Mangohud not working as argument 

### ISSUE THREAD

**Issue by DieALot36T9** [Open-Wine-Components/ULWGL#11]
I used flatpak steam and game launches but I set "mangohud" as argument after .exe which isn't working.

**Comment by GloriousEggroll** [comment]
> I used flatpak steam and game launches but I set "mangohud" as argument after .exe which isn't working.

you have to set mangohud before the gamelauncher, not after the exe. in general mangohud goes before the exe anyway.

also, this has not been tested with flatpak steam, and its not really meant to work with steam. its usecase is for outside of steam.
