### ISSUE TITLE
DNF Repo .conf

### ISSUE THREAD

**Issue by kevinbburns** [Open-Wine-Components/ULWGL#121]
You have RPM releases, and you have the command, but where is the repo?

**Comment by alterNERDtive** [comment]
You download the package from the release page, then you install it.

Edit: turns out, apparently not 🤔

**Comment by kevinbburns** [comment]
I see that @GloriousEggroll  has a COPR repository for Nobra40 that has it, but it wants to replace wayyyyy to many KDE packages and change the identity of the installed system to Nobra. I ended up building it from source, so far so good.

**Comment by GloriousEggroll** [comment]
rpm builds for fedora/nobara are now part of our github actions and provided via artifacts. those artifacts are attached to releases:
https://github.com/Open-Wine-Components/umu-launcher/actions/runs/11333412898
spec file for the build can be found in the packaging folder:
https://github.com/Open-Wine-Components/umu-launcher/tree/main/packaging/rpm
