### ISSUE TITLE
System wise proton-ge which is "proton-ge-custom" not detected

### ISSUE THREAD

**Issue by rairay91** [Open-Wine-Components/ULWGL#123]
In this issue report, I have issue and questions as well. First start with issue:-

I have installed proton-ge-custom(from here https://github.com/GloriousEggroll/proton-ge-custom/, with package manager "pamac") which is always being updated to the latest version with system update. My issue here is that umu-launcher not detecting this proton because this is installed in root directory. However, some other launcher like lutris, steam, heroic easily detect that proton(from root directory).
So inorder to fix this issue I have to first move the proton-ge-custom from this directory /usr/share/steam/compatibilitytools.d/ to this directory /home/"username"/.steam/steam/compatibilitytools.d/. Then I created a softlink to proton-ge-custom in this directory /usr/share/steam/compatibilitytools.d/ which is pointing to this path /home/"username"/.steam/steam/compatibilitytools.d/proton-ge-custom/. Now umu was able to use system wise proton by using this argument(PROTONPATH=proton-ge-custom) in the command line, instead of using (PROTONPATH=GE-Proton).
Why I need to do this, because this will eliminate the headache of redownloading latest proton-ge again and again. I once updated proton-ge with my package manager, it will be updated for everything. This will save bandwidth, resources(I mean system space) e.t.c.

Now coming to my question:- Dose umu download and update same proton-ge which I installed system wise from this source https://github.com/GloriousEggroll/proton-ge-custom/ ?
If so, then why not umu let detect and use system wise installed proton-ge?

**Comment by loathingKernel** [comment]
Umu doesn't support the system-wide steam compatibility tool location by choice. Tools installed there are not necessarily built using the Steam Linux Runtime and as such they might be unfit for use with umu. There is only one case where this is used, and that is the AUR, which makes this use-case the exception, and unlikely to be supported in the future.

If you really want to use a proton installed under `/usr/share/compatibilitytools.d`, you can provide the full path to it through `PROTONPATH=`, but YOU SHOULD NOT USE compiled versions from the AUR with umu, and any issues as a result of that, will be invalid.

**Comment by rairay91** [comment]
Ok, I guess it's maintainer who is responsible for that proton-ge-custom. But your suggestion about giving full path to that proton will help me. And that mean I can still use wine-ge as well with umu.

**Comment by rairay91** [comment]
One more question - What are these meant for "sniper_platform_0.20240618.92328" and "sniper_platform_0.20240423.85483"? Do I need to keep them both, or I can delete the older version, which is "sniper_platform_0.20240423.85483"?

**Comment by R1kaB3rN** [comment]
> One more question - What are these meant for "sniper_platform_0.20240618.92328" and "sniper_platform_0.20240423.85483"? Do I need to keep them both, or I can delete the older version, which is "sniper_platform_0.20240423.85483"?

Those directories are Steam's container runtimes, and it's always safe to delete the older one (sniper_platform_0.20240423.85483) if you already have the new one and if you see the latest version in `VERSIONS.txt` . If you're using the latest version of the launcher (https://github.com/Open-Wine-Components/umu-launcher/commit/dc41d603ceae2d644c274dc94dd40f97d49325d0), you will not have to worry about this as it should automatically delete the old sniper platform directory for you. 

Additionally, I'm expecting users from the RC4 release to have unneeded files in `$HOME/.local/share/umu` now that we're keeping launcher files in its system path. Namely, this should be all of the Python files, `umu_version.json`, `$HOME/.local/share/Steam/compatibilitytools.d/umu-launcher`, `BUILD_ID.txt` and `reaper`. If you have any of those files in those locations, it should be safe to delete them.

**Comment by R1kaB3rN** [comment]
>  Why I need to do this, because this will eliminate the headache of redownloading latest proton-ge again and again. I once updated proton-ge with my package manager, it will be updated for everything. This will save bandwidth, resources(I mean system space) e.t.c.

If you're referring to the AUR and are on Arch Linux, you're actually not saving system resources because `pacman` caches packages by default. So even if the Proton installed in the system path gets updated, you'll still have all of the old Protons in the cache which you'll be responsible of managing yourself.

**Comment by rairay91** [comment]
> > Why I need to do this, because this will eliminate the headache of redownloading latest proton-ge again and again. I once updated proton-ge with my package manager, it will be updated for everything. This will save bandwidth, resources(I mean system space) e.t.c.
> 
> If you're referring to the AUR and are on Arch Linux, you're actually not saving system resources because `pacman` caches packages by default. So even if the Proton installed in the system path gets updated, you'll still have all of the old Protons in the cache which you'll be responsible of managing yourself.

That is why i use package cache cleaner which is provided by garuda linux devs. With just one click i can remove all previous package caches. 👍 Thanks for letting me know how arch linux manages previous package caches.

**Comment by rairay91** [comment]
> > One more question - What are these meant for "sniper_platform_0.20240618.92328" and "sniper_platform_0.20240423.85483"? Do I need to keep them both, or I can delete the older version, which is "sniper_platform_0.20240423.85483"?
> 
> Those directories are Steam's container runtimes, and it's always safe to delete the older one (sniper_platform_0.20240423.85483) if you already have the new one and if you see the latest version in `VERSIONS.txt` . If you're using the latest version of the launcher ([dc41d60](https://github.com/Open-Wine-Components/umu-launcher/commit/dc41d603ceae2d644c274dc94dd40f97d49325d0)), you will not have to worry about this as it should automatically delete the old sniper platform directory for you.
> 
> Additionally, I'm expecting users from the RC4 release to have unneeded files in `$HOME/.local/share/umu` now that we're keeping launcher files in its system path. Namely, this should be all of the Python files, `umu_version.json`, `$HOME/.local/share/Steam/compatibilitytools.d/umu-launcher`, `BUILD_ID.txt` and `reaper`. If you have any of those files in those locations, it should be safe to delete them.

Yes these files and directories were there from previous build. If you know any more files or directories please let us know, so we can remove unneeded files.

**Comment by R1kaB3rN** [comment]
> > > One more question - What are these meant for "sniper_platform_0.20240618.92328" and "sniper_platform_0.20240423.85483"? Do I need to keep them both, or I can delete the older version, which is "sniper_platform_0.20240423.85483"?
> > 
> > 
> > Those directories are Steam's container runtimes, and it's always safe to delete the older one (sniper_platform_0.20240423.85483) if you already have the new one and if you see the latest version in `VERSIONS.txt` . If you're using the latest version of the launcher ([dc41d60](https://github.com/Open-Wine-Components/umu-launcher/commit/dc41d603ceae2d644c274dc94dd40f97d49325d0)), you will not have to worry about this as it should automatically delete the old sniper platform directory for you.
> > Additionally, I'm expecting users from the RC4 release to have unneeded files in `$HOME/.local/share/umu` now that we're keeping launcher files in its system path. Namely, this should be all of the Python files, `umu_version.json`, `$HOME/.local/share/Steam/compatibilitytools.d/umu-launcher`, `BUILD_ID.txt` and `reaper`. If you have any of those files in those locations, it should be safe to delete them.
> 
> Yes these files and directories were there from previous build. If you know any more files or directories please let us know, so we can remove unneeded files.

Yes, we should mention them in a changelog file or Github release notes in the next release. Also, [since the question of using system installed protons or custom protons seems to be common](https://github.com/Open-Wine-Components/umu-launcher/issues/88), this has been added to the [project's FAQ page](https://github.com/Open-Wine-Components/umu-launcher/wiki/Frequently-asked-questions-(FAQ)).

In the future, any more issues that are related to this will be closed instantly.

**Comment by R1kaB3rN** [comment]
Closing as this issue is a duplicate and should be addressed
