### ISSUE TITLE
UMU-Proton is using an older version of VKD3D

### ISSUE THREAD

**Issue by Faugus** [Open-Wine-Components/ULWGL#124]
I checked what version UMU-Proton is using and it's an older build from December 2023, the [Version 2.11.1](https://github.com/HansKristian-Work/vkd3d-proton/releases/tag/v2.11.1) and not the build from May 2024, the [Version 2.12](https://github.com/HansKristian-Work/vkd3d-proton/releases/tag/v2.12).

A newer version of VKD3D was released today, the [Version 2.13](https://github.com/HansKristian-Work/vkd3d-proton/releases/tag/v2.13).

![image](https://github.com/Open-Wine-Components/umu-launcher/assets/112667550/7e721be9-3d6a-4707-a239-19a57fa272ff)

**Comment by R1kaB3rN** [comment]
This issue as well as https://github.com/Open-Wine-Components/umu-launcher/issues/89 should be addressed in the next release.

UMU-Proton follows the stable releases of upstream's stable Proton. Therefore, you can expect the version to be bumped to _[2.12](https://github.com/HansKristian-Work/vkd3d-proton/tree/f6d39052afb1fbc490b711769a0dd91c12340251)_ in the next release but not to _2.13_.

**Comment by R1kaB3rN** [comment]
Closing as [UMU-Proton was recently updated](https://github.com/Open-Wine-Components/umu-proton/releases/tag/UMU-Proton-9.0-2) to [upstream's VKD3D](https://github.com/HansKristian-Work/vkd3d-proton/tree/f6d39052afb1fbc490b711769a0dd91c12340251)
