### ISSUE TITLE
Prevent running on musl

### ISSUE THREAD

**Issue by sewnie** [Open-Wine-Components/ULWGL#13]
Musl systems such as mine cannot run the Steam runtime due to it being linked to Steam. If possible, there should be some sort of possible musl build or a musl check to prevent running on musl

**Comment by GloriousEggroll** [comment]
What do you mean "due to it being linked to steam"?

This runs completely independant from steam and does not require the steam application

**Comment by GloriousEggroll** [comment]
Also, I've managed to flatpak ULWGL, so even if it's on a Musl system it should still run via flatpak if flatpak is supported

**Comment by GloriousEggroll** [comment]
While I agree a check for native musl would probably be needed here, I can confirm the flatpak tested does run on Muscl systems -- tested on Alpine a few minutes ago.
![Screenshot_20240205_181403](https://github.com/Open-Wine-Components/ULWGL-launcher/assets/11287837/5b50d0c1-6edf-4b47-88e6-4ee8ffe4c88f)

**Comment by GloriousEggroll** [comment]
latest rc has a local flatpak repo tarballed for testing:
https://github.com/Open-Wine-Components/ULWGL-launcher/releases/tag/0.1-RC3
