### ISSUE TITLE
Option to disable auto updates on startup

### ISSUE THREAD

**Issue by AdamantGarth** [Open-Wine-Components/ULWGL#134]
I'd like to be able to disable steamrt/proton updates on umu startup (using an environment variable, for example), and trigger them manually from time to time.

**Comment by R1kaB3rN** [comment]
I believe we want users to always use the latest runtime and Proton, and if we add an option it'll need to be sometime after the next release.

Though, would you still wish for this feature if the updates for those builds were faster? Because I would understand the annoyance for waiting for the updates for those builds to complete before running the game.

**Comment by AdamantGarth** [comment]
> I believe we want users to always use the latest runtime and Proton

As a user I do too, and I'm very happy that umu can update these things itself. But sometimes I have to use metered connections that are both too slow and too expensive to be downloading hundreds of megabytes of runtimes on. I doubt that there's a way to reduce the size of these runtimes to be both fast and cheap to download on such connections, so an option to disable the auto updates would be much appreciated.

**Comment by db47h** [comment]
Another use case for this is when your broadband connection goes down: umu just crashes on a failing DNS query (my local net was still up but no external name resolution would work). Although for that specific case a more graceful handling of network errors would be nice, an option to disable updates would probably be simpler to implement.

**Comment by gabriele2000** [comment]
Guys, just hear me out: DELTA UPDATES

**Comment by R1kaB3rN** [comment]
Graceful handling of network errors will be explored in the future. Same with delta updates once we start [customizing the runtime](https://github.com/Open-Wine-Components/umu-launcher/issues/4), as the delta file would need to be created at build time.
