### ISSUE TITLE
Nix package failed to build

### ISSUE THREAD

**Issue by DCsunset** [Open-Wine-Components/ULWGL#142]
When I'm trying to build to package using flake with command `nix build ./packaging/nix\#umu`, the following error occurred:

```
Running phase: buildPhase
build flags: SHELL=/nix/store/h3bhzvz9ipglcybbcvkxvm4vg9lwvqg4-bash-5.2p26/bin/bash
/nix/store/h3bhzvz9ipglcybbcvkxvm4vg9lwvqg4-bash-5.2p26/bin/bash: line 1: /usr/bin/python3: No such file or directory
/nix/store/h3bhzvz9ipglcybbcvkxvm4vg9lwvqg4-bash-5.2p26/bin/bash: line 1: git: command not found
:: Updating umu/umu_version.json
/nix/store/h3bhzvz9ipglcybbcvkxvm4vg9lwvqg4-bash-5.2p26/bin/bash: line 1: git: command not found
cp umu/umu_version.json.in umu/umu_version.json.in.tmp
sed 's|##UMU_VERSION##||g' -i umu/umu_version.json.in.tmp
mv umu/umu_version.json.in.tmp umu/umu_version.json
:: Building umu man pages
scdoc < docs/umu.1.scd > builddir/umu.1
scdoc < docs/umu.5.scd > builddir/umu.5
touch builddir/.build-umu-docs
:: Building umu-launcher
sed 's|##INSTALL_PATH##|/umu/umu_run.py|g' umu/umu-launcher/umu-run.in > builddir/umu-launcher-run
touch builddir/.build-umu-launcher
@nix { "action": "setPhase", "phase": "installPhase" }
Running phase: installPhase
install flags: SHELL=/nix/store/h3bhzvz9ipglcybbcvkxvm4vg9lwvqg4-bash-5.2p26/bin/bash install
/nix/store/h3bhzvz9ipglcybbcvkxvm4vg9lwvqg4-bash-5.2p26/bin/bash: line 1: /usr/bin/python3: No such file or directory
/nix/store/h3bhzvz9ipglcybbcvkxvm4vg9lwvqg4-bash-5.2p26/bin/bash: line 1: git: command not found
:: Installing umu_version.json
install -d /umu
install: cannot change permissions of '/umu': No such file or directory
make: *** [Makefile.in:60: version-install] Error 1
```

To fix some of the above errors, I add `git` to dependencies and set python interpreter accordingly.
But there are still some other errors:

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/wbdbk6qnx9csqr0zbjyyazi8g7wi6mip-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
patching script interpreter paths in ./configure.sh
./configure.sh: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/h3bhzvz9ipglcybbcvkxvm4vg9lwvqg4-bash-5.2p26/bin/bash"
configure flags: --prefix=/nix/store/ilijjk8cd8xbdy1n1621rv8wjdfpxqmq-umu-launcher-0.1
:: Created ./Makefile, now run "make" to build.
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
build flags: SHELL=/nix/store/h3bhzvz9ipglcybbcvkxvm4vg9lwvqg4-bash-5.2p26/bin/bash PYTHON_INTERPRETER=/nix/store/k3701zl6gmx3la7y4dnflcvf3xfy88kh-python3-3.11.9/bin/python3 DESTDIR=\$\(out\)
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
:: Updating umu/umu_version.json
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cp umu/umu_version.json.in umu/umu_version.json.in.tmp
sed 's|##UMU_VERSION##||g' -i umu/umu_version.json.in.tmp
mv umu/umu_version.json.in.tmp umu/umu_version.json
:: Building umu man pages
scdoc < docs/umu.1.scd > builddir/umu.1
scdoc < docs/umu.5.scd > builddir/umu.5
touch builddir/.build-umu-docs
:: Building umu-launcher
sed 's|##INSTALL_PATH##|/nix/store/k3701zl6gmx3la7y4dnflcvf3xfy88kh-python3-3.11.9/lib/python3.11/site-packages/umu/umu_run.py|g' umu/umu-launcher/umu-run.in > builddir/umu-launcher-run
touch builddir/.build-umu-launcher
@nix { "action": "setPhase", "phase": "installPhase" }
Running phase: installPhase
install flags: SHELL=/nix/store/h3bhzvz9ipglcybbcvkxvm4vg9lwvqg4-bash-5.2p26/bin/bash PYTHON_INTERPRETER=/nix/store/k3701zl6gmx3la7y4dnflcvf3xfy88kh-python3-3.11.9/bin/python3 DESTDIR=\$\(ou>
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
:: Installing umu_version.json
install -d /nix/store/ilijjk8cd8xbdy1n1621rv8wjdfpxqmq-umu-launcher-0.1/nix/store/k3701zl6gmx3la7y4dnflcvf3xfy88kh-python3-3.11.9/lib/python3.11/site-packages/umu
install -Dm 644 umu/umu_version.json -t /nix/store/ilijjk8cd8xbdy1n1621rv8wjdfpxqmq-umu-launcher-0.1/nix/store/k3701zl6gmx3la7y4dnflcvf3xfy88kh-python3-3.11.9/lib/python3.11/site-packages/umu
:: Building umu
/nix/store/k3701zl6gmx3la7y4dnflcvf3xfy88kh-python3-3.11.9/bin/python3 -m build --wheel --skip-dependency-check --no-isolation --outdir=builddir
/nix/store/k3701zl6gmx3la7y4dnflcvf3xfy88kh-python3-3.11.9/bin/python3: No module named build
make: *** [Makefile.in:83: builddir/.build-umu-dist] Error 1
```

There are some git errors in the middle but I'm not sure if there are relevant, but the python error at the end results in the failure of make command.

**Comment by R1kaB3rN** [comment]
There are new build requirements for umu-launcher as the project just recently moved to being a Python module installed in Python's `site-packages` directory.

See https://github.com/Open-Wine-Components/umu-launcher?tab=readme-ov-file#building.

As for the git error, it must be something wrong in the build process as git seems to be trying to traverse the filesystem outside the repo. This problem should have been addressed in https://github.com/Open-Wine-Components/umu-launcher/commit/a1182f750d2883fc1d76014f397d69ff672effde

cc @beh-10257

**Comment by bohanubis** [comment]
I didn't update my system for like a week sorry for missing this
yeah I will try to fix this tomorrow

**Comment by bohanubis** [comment]
@R1kaB3rN is there any plans to add a setup.py
since well yeah doing this is well getting complicated
and I don't really feel like patching the project just to add nix support
aka make the project installable in regular distros aka (non mutable)
using `pip install .`

**Comment by bohanubis** [comment]
yeah this is gonna take me another day I guess this is my skill issue
(actually if you can add setup.py it will make my life a lot easier)

**Comment by bohanubis** [comment]
anyway I found a solution
its 1 am here but the game works yaaaay
I will fix this as soon as I wake up tomorrow sorry for delay
but there is another problem unrelated to packaging

@R1kaB3rN 
do you have any idea what these errors mean (they show up but the game works either way)
![image](https://github.com/Open-Wine-Components/umu-launcher/assets/77834479/d08aac2b-b83e-489f-8c9f-d7f6c3f59d49)

also for all intents and purposes my DISPLAY variable is :0
I don't understand why its complaining about :1

**Comment by R1kaB3rN** [comment]
> anyway I found a solution its 1 am here but the game works yaaaay I will fix this as soon as I wake up tomorrow sorry for delay but there is another problem unrelated to packaging
> 
> @R1kaB3rN do you have any idea what these errors mean (they show up but the game works either way) ![image](https://private-user-images.githubusercontent.com/77834479/347612854-d08aac2b-b83e-489f-8c9f-d7f6c3f59d49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NDk1OTgsIm5iZiI6MTcyMDY0OTI5OCwicGF0aCI6Ii83NzgzNDQ3OS8zNDc2MTI4NTQtZDA4YWFjMmItYjgzZS00ODlmLThjOWYtZDdmNmMzZjU5ZDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDIyMDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYThiYTRhZTU3OGJlMmJhNDkzYzA3MzhhNTkzYTdlZTliNWI4ZWUzYTRmNDgyY2U2YTE4YjY2MTFkNjdlMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KJULCHlbdcUd_E5oHpBM2ZukdAaxnje6vCgbOl_CMXQ)
> 
> also for all intents and purposes my DISPLAY variable is :0 I don't understand why its complaining about :1

Since I know you use bwrap, does umu-run in that instance happen to be under bwrap? If that error doesn't occur without using it, then your bwrap configuration needs to be updated.

**Comment by bohanubis** [comment]
@R1kaB3rN its happening without bwrap

**Comment by R1kaB3rN** [comment]
> @R1kaB3rN its happening without bwrap

Do you happen to be using gamescope? Looking at the traceback, in order to reach line 647, you would need to be using gamescope as the launcher was able to somehow retrieve a base layer order sequence from display server 0. 

If you were not using gamescope, then I think this is a bug.
