### ISSUE TITLE
Symlinking current unix username to `steamuser`

### ISSUE THREAD

**Issue by loathingKernel** [Open-Wine-Components/ULWGL#15]
As a result of Valve's wine hardcoding the wine user name to `steamuser`, prefixes created with other wine versions, even `wine-ge` will lose access to the wine user directory named after the current unix user. It will also cause games to lose access to user-local files in case the user choose another runner not based on proton/ulwgl.

Since the general consensus is to keep compatibility with wine, for minimum disruption, `ulwgl-run` should also create a symlink named  `drive_c/users/<unix_username>` pointing to `drive_c/users/steamuser`.

**Comment by GloriousEggroll** [comment]
fwiw -- wine-ge actually doesnt have this problem because we strip the steam-specific patches from it (not game related ones), but I like the idea

**Comment by loathingKernel** [comment]
I was using it as an example for prefixes previously created with wine-ge, that now might be used with ulwgl. They will have the user folder under the current unix name since as you said have the valve specific patches stripped, which should now also appear as `steamuser`. Likely some checking needs to be involved, and moving the `<username>` folder to `steamuser` and symlink it back.

**Comment by R1kaB3rN** [comment]
I see, but we could just patch that specific functionality out, right? However, if I'm not mistaken, this should be simple and relatively safe if we decide to create a symlink instead...

**Comment by loathingKernel** [comment]
IMO it is better to just handle it in the filesystem level, without touching the proton source, as steam relies on it for things including but not limited to cloud saves.
