### ISSUE TITLE
Not working on Fedora anymore

### ISSUE THREAD

**Issue by Faugus** [Open-Wine-Components/ULWGL#157]
I'm getting this error in a fresh installation of Fedora (it was working before):
```
MANGOHUD=1 WINEPREFIX=/home/faugus/.config/faugus-launcher/prefixes/world-of-warcraft GAMEID=world-of-warcraft "/usr/bin/umu-run" "/mnt/data/Games/World of Warcraft/_classic_era_/WowClassic.exe"
steamrt is up to date
UMU-Proton is up to date
Traceback (most recent call last):
  File "/usr/bin/umu-run", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/__main__.py", line 9, in main
    return umu_run()
           ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/umu_run.py", line 780, in main
    return run_command(command)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/umu_run.py", line 643, in run_command
    gamescope_baselayer_sequence = get_gamescope_baselayer_order()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/umu/umu_run.py", line 511, in get_gamescope_baselayer_order
    d = display.Display(":0")
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.12/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
```
```
echo $DISPLAY
:0
```
I tried the copr package:
https://copr.fedorainfracloud.org/coprs/gloriouseggroll/nobara-40/package/umu-launcher/
And building the rpm package as described here:
https://github.com/Open-Wine-Components/umu-launcher/blob/main/packaging/rpm/README.md
Both present the same error.

**Comment by R1kaB3rN** [comment]
If you're using GloriousEggroll's copr package, it pulls from commit ecd3d90144f433a877b45c7a7e53870cd6cd8d73 which is why as the display problem has been addressed in main at commit 295c7b8d3e42081860beb859ff49045a826506b3.

After a rebuild, the RPM build instructions need to be updated too since it's still referencing Fedora 39.

cc @GloriousEggroll

**Comment by Faugus** [comment]
> After a rebuild, the RPM build instructions need to be updated too since it's still referencing Fedora 39.

What instructions are you refering to? That's how I'm building the rpm package:
```
fedpkg --release f40 srpm
mock -r /etc/mock/fedora-40-x86_64.cfg --rebuild --enable-network *.src.rpm
sudo mv /var/lib/mock/fedora-40-x86_64/result .
```

**Comment by GloriousEggroll** [comment]
resolved:
spec sheet commit updated: e2dc7374b9d0ff7fe3b8fc2d722213973d1b56aa
build instructions updated: b788d6d7ab6a96593884cfb76a403094d55af522
nobara build updated: https://copr.fedorainfracloud.org/coprs/gloriouseggroll/nobara-40/build/7777017/
tested and working with zenless zone zero
