### ISSUE TITLE
Debian packaging: can't build with source format '3.0 (quilt)'

### ISSUE THREAD

**Issue by billbeans** [Open-Wine-Components/ULWGL#161]
Trying to build a deb package on Debian 12, following the instructions here: https://github.com/Open-Wine-Components/umu-launcher/tree/main/packaging/deb

When I get to the `dpkg-buildpackage --no-sign` step, I am met with this error:

```
dpkg-source: info: using options from umu-launcher/debian/source/options: --extend-diff-ignore=Makefile
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../umu-launcher_1.0.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: error: dpkg-source -b . subprocess returned exit status 2
```

**Comment by billbeans** [comment]
To get around this, I removed the format file (`mv debian/source/format debian/source/format_bak`), then at least the build completed successfully. But once I tried to install the deb packages, it failed because Debian 12's version of `python3-filelock` is too old, so I downloaded and installed the version in the stable testing (Trixie) repository, linked below. There were no dependency problems, so I think this should be ok.

https://packages.debian.org/trixie/all/python3-filelock/download

**Comment by R1kaB3rN** [comment]
Thanks for reporting this. 

cc @CosmicFusion for the `dpkg-buildpackage` error and if it's possible to catch this in the CI.

**Comment by R1kaB3rN** [comment]
I believe the Debian package instructions in the repo assumes that the platform is Ubuntu 24.04 (Noble Numbat), hence I specified the minimum version for `python3-filelock` to be at least `3.13.1`. 

Though given that this is for a .deb package, perhaps the version should be lowered at another version...

**Comment by GloriousEggroll** [comment]
verified latest debian specific build files compile, install, and run on debian 12. package build artifacts located here: https://github.com/Open-Wine-Components/umu-launcher/actions/runs/11332994028

 closing this issue.
