### ISSUE TITLE
gstreamer: libavfilter.so not found

### ISSUE THREAD

**Issue by MadByteDE** [Open-Wine-Components/ULWGL#167]
**Version:** UMU-Proton-9.0-2
**Distro:** Fedora Linux 40
**DE:** KDE Plasma (Wayland)
**CPU:** AMD Ryzen 7 5800X3D
**MEM:** 24GB DDR4
**GPU:** Nvidia GeForce RTX 4070

Sorry for posting this here, but I couldn't find a bug tracker / issues page for the UMU-Proton project :/

```log
(wine:5449): GStreamer-WARNING **: 08:39:02.486: Failed to load plugin '/home/USER/.local/share/Steam/compatibilitytools.d/UMU-Proton-9.0-2/files/lib64/gstreamer-1.0/libgstlibav.so': libavfilter.so.7: cannot open shared object file: No such file or directory

(wine:5449): GStreamer-WARNING **: 08:39:02.487: Failed to load plugin '/home/USER/.local/share/Steam/compatibilitytools.d/UMU-Proton-9.0-2/files/lib/gstreamer-1.0/libgstlibav.so': /home/USER/.local/share/Steam/compatibilitytools.d/UMU-Proton-9.0-2/files/lib/gstreamer-1.0/libgstlibav.so: wrong ELF class: ELFCLASS32
```
Looks like gstreamer is missing some plugins in the container for me, resulting in the errors seen in the proton log attached below.

I'm playing Escape from Tarkov through **Lutris (Native)**.

The video(s) play just fine using `wine-ge`. 

![2024-08-06_19-43](https://github.com/user-attachments/assets/fedcf7b9-9849-40b7-adcc-d1560b56a3d5)
[steam-default.log](https://github.com/user-attachments/files/16539139/steam-default.log)

**Comment by layercak3** [comment]
Neither Proton/UMU-Proton nor the downloaded sniper runtime contain ffmpeg libraries. (With steam, apparently Valve does bundle some ffmpeg libraries with Steam and the proton script adds them to the library path)
You can use GE-Proton which comes with a proper gstreamer and ffmpeg installation.

**Comment by MadByteDE** [comment]
> Neither Proton/UMU-Proton nor the downloaded sniper runtime contain ffmpeg libraries. (With steam, apparently Valve does bundle some ffmpeg libraries with Steam and the proton script adds them to the library path) You can use GE-Proton which comes with a proper gstreamer and ffmpeg installation.

You're right, downloading `GE-Proton9-11` e.g. using `protonup-qt` does indeed work.

For some odd reason the default `GE-Proton (Latest)` option offered in Lutris does not use the same GE-Proton version, but instead uses the latest `UMU-Proton` one - which doesn't work in that regard. Maybe the Lutris devs need to adjust the naming for that, hmm...

I gonna close this as this seems to be an issue with something else and not UMU-Proton itself.
Thanks!

**Comment by alterNERDtive** [comment]
> For some odd reason the default `GE-Proton (Latest)` option offered in Lutris does not use the same GE-Proton version

Set `PROTONPATH=GE-Proton` somewhere.
