### ISSUE TITLE
Space Engineers not launching

### ISSUE THREAD

**Issue by mistermookiefun** [Open-Wine-Components/ULWGL#173]
Hey everyone!
Downloaded the last version of umu-launcher with ProtonGE 9.2
I'm trying to play Space Engineers that is owned on my steam account.
I tried this:
` WINEPREFIX=/x/y/z/Games/Space_engineers/ GAMEID=umu-5244850 PROTONPATH=~/.local/share/Steam/compatibilitytools.d/GE-Proton9-2/ umu-run steam.exe`
Get this error:
`steam-runtime-steam-remote: Steam is not running: No such device or address`
And tried :
` WINEPREFIX=/x/y/z/Games/Space_engineers/ GAMEID=umu-5244850 PROTONPATH=~/.local/share/Steam/compatibilitytools.d/GE-Proton9-2/ NOSTEAM=1 umu-run steamapps/common/SpaceEngineers/Bin64/SpaceEngineers.exe `but the game just crashes.
I also tried the last command without NOSTEAM=1 to try to inject the steam token/validation but no luck.
Any idea on how to run my Space Engineers?
Thanks :D

**Comment by R1kaB3rN** [comment]
Currently, umu-launcher does not handle the subdirectory case for games. [See this issue for more context](https://github.com/Open-Wine-Components/umu-launcher/issues/63). This problem can be solved and will be revisited in the future.

So given that a subdirectory `Bin64` exists within the main game's directory, it tells me that this is a game that requires to be executed from that subdirectory. [steamdb supports this fact](https://steamdb.info/app/244850/config/), as a launch option `Bin64\SpaceEngineers.exe` is defined for it. Therefore, please try rerunning the game within `Bin64`.

**Comment by mistermookiefun** [comment]
Hey! Thanks for the reply.
The problem with that technique is that it won't launch, probably because it can't fetch my SteamID or Steam authorization or something like that?
I would like to start steam.exe withumu and  the space engineers patches to launch it via the Steam Library? Is that possible?

**Comment by loathingKernel** [comment]
If it is a Steam game, use Steam. Umu is for non-steam games.

**Comment by R1kaB3rN** [comment]
Related to https://github.com/Open-Wine-Components/umu-launcher/issues/105

Closing as currently not planned for now as it would be Steam specific/dependent. Supporting Steam games requires special handling of Steam's DRM and for users to have its client installed, which would be contradictory to the project's goals of not requiring to have it installed.

**Comment by mistermookiefun** [comment]
Thank you all
