### ISSUE TITLE
Inclusion of `reaper` with ULWGL

### ISSUE THREAD

**Issue by loathingKernel** [Open-Wine-Components/ULWGL#18]
Steam uses [`reaper`](https://github.com/Plagman/reaper) to keep track of processes, which is important because games, especially though Wine, can spawn multiple separate processes, such as dedicated launchers. Because `reaper` is part of the base Steam runtime as `~/.local/share/Steam/ubuntu12_32/reaper`, it is unavailable to ULWGL. I think it would be helpful to be included.

1. It can become part of the ULWGL-launcher runtime, as a compiled binary from the repository above.

2. It can be included as a python script. @strycore, if I am not mistaken you have a more advanced implementation of it as [`lutris-wrapper`](https://github.com/lutris/lutris/blob/master/share/lutris/bin/lutris-wrapper). Would it be possible to use that implementation as a replacement?

**Comment by GloriousEggroll** [comment]
it may be useful but afaik lutris already has a process tracking method, heroic possibly does as well. im not sure how beneficial it would be to have them swap or if its useful @imLinguin @mirkobrombin

**Comment by imLinguin** [comment]
In heroic both gogdl and nile act like a reaper utility already. Legendary is the only exception at the moment.
I believe we could switch to one common reaper binary.

I don't know if it's really needed to have it in ULWGL, in Heroic and Lutris we need our own wrappers nevertheless to handle native runners.

**Comment by GloriousEggroll** [comment]
I'm wondering if this would be useful for EGS. I noticed it stays open (at least in lutris). 
Egs opens, then the game opens, then you close the game, then you have to manually close egs, and still it lingers open int he background

**Comment by GloriousEggroll** [comment]
yeah I just confirmed reaper works perfectly for making sure egs closes completely. honestly I suppose it wouldnt hurt to just run reaper nested inside whatever other wrappers
in fact it would stop lutris from having to do things like try to exempt battle.net agent during install and other applications that are picky about monitoring

**Comment by GloriousEggroll** [comment]
How about something like this?:
```
PARENT=$(cat /proc/$PPID/cmdline | tr '[:upper:]' '[:lower:]')

echo $PARENT
echo $PPID
echo $(cat /proc/$PPID/cmdline)

# Use reaper as process monitor if no other known monitors are in use.
case "$PARENT" in
  *lutris-wrapper*)
    echo "Parent process is lutris-wrapper (Lutris process monitor), reaper will not be used."
    ;;
  *nile*)
    echo "Parent process is nile (Amazon Games process monitor), reaper will not be used."
    ;;
  *gogdl*)
    echo "Parent process is gogdl (GOG Games process monitor), reaper will not be used."
    ;;
  *)
    REAPER="$here/reaper GameId=$ULWGL_ID -- "
    ;;
esac

if [ -z "$REAPER" ]; then
 "$here"/ULWGL "--verb=$PROTON_VERB" -- "$PROTONPATH"/proton "$PROTON_VERB" "$EXE" "$@"
 else
  $REAPER "$here"/ULWGL "--verb=$PROTON_VERB" -- "$PROTONPATH"/proton "$PROTON_VERB" "$EXE" "$@"
fi
```

**Comment by mirkobrombin** [comment]
> it may be useful but afaik lutris already has a process tracking method, heroic possibly does as well. im not sure how beneficial it would be to have them swap or if its useful @imLinguin @mirkobrombin

Bottles doesn't implement a real reaper mechanism for process management. Instead, it utilizes the `WineExecutor` class, optionally in conjunction with `WineBridge`, to manage wine processes. For process monitoring we use `winedbg` to keep track of the process state, informing Bottles about its status. However, this setup does not involve checking for or handling zombie processes and similar low-level process management tasks typically associated with a reaper. Anyway, Bottles is currently being entirely redeveloped. As such, the upcoming version might leverage a reaper if it becomes available through ULWGL.

**Comment by GloriousEggroll** [comment]
> > it may be useful but afaik lutris already has a process tracking method, heroic possibly does as well. im not sure how beneficial it would be to have them swap or if its useful @imLinguin @mirkobrombin
> 
> Bottles doesn't implement a real reaper mechanism for process management. Instead, it utilizes the `WineExecutor` class, optionally in conjunction with `WineBridge`, to manage wine processes. For process monitoring we use `winedbg` to keep track of the process state, informing Bottles about its status. However, this setup does not involve checking for or handling zombie processes and similar low-level process management tasks typically associated with a reaper. Anyway, Bottles is currently being entirely redeveloped. As such, the upcoming version might leverage a reaper if it becomes available through ULWGL.

In that case I think its a good idea to include it as a default. there are more edge cases where its needed than not + if the goal is for all launchers (projects outside lutris/bottles/heroic) to use it then we dont know if they have one as well, and it doesnt hurt to run reaper inside one if they do anyways.

**Comment by R1kaB3rN** [comment]
Reaping child processes can also be performed through bubblewrap by specifying the `--die-with-parent` option. Though, I can't say how effective it would be compared to Reaper/Lutris's solution or about the potential overhead it would incur. 

I can also confirm that this method works if extending it as the first command in the launcher script. However, this would only be successful if we decide to implement _v2-entry-point in Python. Because it seems for some reason, bwrap is unable to locate the files -- ULWGL and run

**Comment by GloriousEggroll** [comment]
Just go with reaper, the goal is to do things the same way valve does, and reaper itself is open source. We can compile it ourselves later on. For now the ol' copypasta will do.
