### ISSUE TITLE
Alan Wake 2 incorrectly detects as being installed on a HDD [Heroic]

### ISSUE THREAD

**Issue by Sid127** [Open-Wine-Components/ULWGL#181]
I'm using Heroic Games Launcher's experimental UMU integration, and Alan Wake 2 incorrectly detects as being installed on a HDD, bringing up the pop up on every launch.

**Comment by GloriousEggroll** [comment]
this would be a wine/proton issue, not an umu-launcher issue. since its not a steam game it would be an issue to report to upstream wine. the game thinking it's on an HDD is something in wines code that makes it think that.
