### ISSUE TITLE
kingdom hearts 1.5 + 2.5 hd remix not launching in game mode 

### ISSUE THREAD

**Issue by DevilzAvacado** [Open-Wine-Components/ULWGL#184]
hi, i've recently gotten my steam deck oled and have been enjoying it since. went through a couple games already and wanted to play the kh games since i got them in a deep discount a bit back on an a sale on epic games. i'm using heroic games launcher. everything works except for controller in desktop mode including the fmv. but in game mode it wont even launch. idk if it will help but here is the log i got from heroic.
[68c214c58f694ae88c2dab6f209b43e4-lastPlay.log](https://github.com/user-attachments/files/16999911/68c214c58f694ae88c2dab6f209b43e4-lastPlay.log)

**Comment by R1kaB3rN** [comment]
The problem of games not launching in the Steam Deck's game mode has already been solved at https://github.com/Open-Wine-Components/umu-launcher/commit/6ff8c44b52f33d89b2e3b06cd33e3f6ec70c3318. See https://github.com/Open-Wine-Components/umu-launcher/issues/92 for the tracked issue.

At this point, it will be up to Heroic to update their bundled umu-launcher. If you're interested to know their timeline, I invite you to ask the team at their Discord channel. In the meantime, you can take action yourself by [updating its bundled umu by following these steps](https://github.com/Open-Wine-Components/umu-launcher/issues/182#issuecomment-2345109091). I believe it should work, as long as you change the path to Heroic's runtime directory and **not** delete the `current_version` file.

Edit:
The Heroic Launcher (Flatpak) should have its files in `.var`.

**Comment by R1kaB3rN** [comment]
Closing as this is not a _current_ bug in the launcher.
