### ISSUE TITLE
How to run Steam app itself

### ISSUE THREAD

**Issue by m1dr3d** [Open-Wine-Components/ULWGL#189]
So I could run steam.exe using wine-ge, but because of its outdatedness I decided to ask you about this.

`$ WINEPREFIX=/home/m1dr3d/Games/Steam GAMEID=umu-dauntless PROTONPATH=/usr/share/steam/compatibilitytools.d/proton-ge-custom/ umu-run "/home/m1dr3d/Games/Steam/drive_c/Program Files (x86)/Steam/Steam.exe"
steamrt is up to date
pressure-vessel-wrap[47747]: W: Not sharing path STEAM_COMPAT_MOUNTS="...:/usr/share/steam/compatibilitytools.d/proton-ge-custom:..." with container because "/usr" is reserved by the container framework
ProtonFixes[47835] INFO: Running protonfixes
ProtonFixes[47835] INFO: Running checks
ProtonFixes[47835] INFO: All checks successful
ProtonFixes[47835] INFO: Non-steam game UNKNOWN (umu-dauntless)
ProtonFixes[47835] INFO: No store specified, using UMU database
ProtonFixes[47835] INFO: Using global defaults for UNKNOWN (umu-dauntless)
ProtonFixes[47835] INFO: Non-steam game UNKNOWN (umu-dauntless)
ProtonFixes[47835] INFO: No store specified, using UMU database
ProtonFixes[47835] INFO: No global protonfix found for UNKNOWN (umu-dauntless)
Proton: /home/m1dr3d/Games/Steam/drive_c/Program Files (x86)/Steam/Steam.exe
Proton: Executable a unix path, launching with /unix option.
wine: using kernel write watches, use_kernel_writewatch 1.
fsync: up and running.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
steam-runtime-steam-remote[47911]: W: sd_journal_stream_fd: Connection refused
steam-runtime-steam-remote: Steam is not running: No such device or address
steam-runtime-steam-remote[47914]: W: sd_journal_stream_fd: Connection refused
steam-runtime-steam-remote: Steam is not running: No such device or address`

**Comment by R1kaB3rN** [comment]
One of the project's goals is to not require Steam installed or have its process running to launch games. Judging from the log, this game looks to be locked behind Steam's DRM:

> Connection refused steam-runtime-steam-remote: Steam is not running: No such device or address

Therefore, this makes this case being Steam specific/dependent which would be contradictory to the project's goals.

See https://github.com/Open-Wine-Components/umu-launcher/issues/173
