### ISSUE TITLE
Accessing external drives with umu-run

### ISSUE THREAD

**Issue by NelloKudo** [Open-Wine-Components/ULWGL#195]
Steam's runtime only gives access to a few system directories (/home, /media and a few others) but should be configurable to also access other disks mounted at others paths (ex. /data). 

I know Steam relies on `STEAM_COMPAT_MOUNTS` for this, but it's not working with umu, is there any alternative for it?

**Comment by R1kaB3rN** [comment]
Besides creating symbolic links at `$HOME/.local/share/umu` to point to your external drives or the Steam Runtime's default paths, no.  However, I think this is a reasonable request and supporting this use case would be trivial.

**Comment by R1kaB3rN** [comment]
So after looking into this, there's actually a few ways we can do it:

- STEAM_COMPAT_MOUNTS
- PRESSURE_VESSEL_FILESYSTEMS_RW
- PRESSURE_VESSEL_FILESYSTEMS_RO

umu-launcher currently does not respect `STEAM_COMPAT_MOUNTS` from the host environment and will override it with `$HOME/.local/share/umu:$PROTONPATH`. Not really sure we should, if there's already more than one way to do it -- `PRESSURE_VESSEL_FILESYSTEMS_RW` and `PRESSURE_VESSEL_FILESYSTEMS_RO`.

See https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/slr-for-game-developers.md#making-more-files-available-in-the-container

**Comment by R1kaB3rN** [comment]
In addition to the above,  setting `STEAM_COMPAT_LIBRARY_PATHS` is also valid.

Closing as completed as there is already more than 1 way to achieve this.

Also, I already went ahead  and [documented this question in the project's wiki](https://github.com/Open-Wine-Components/umu-launcher/wiki/Frequently-asked-questions-(FAQ)) as I am expecting this to be a common question.

**Comment by NelloKudo** [comment]
Tested it here as well and whereas `STEAM_COMPAT_LIBRARY_PATHS` seems to not be working, `PRESSURE_VESSEL_FILESYSTEMS_RW` does. Thanks for the help!
