### ISSUE TITLE
Any advantages over PortProton?

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [Open-Wine-Components/ULWGL#200]
I'm using now https://github.com/Castro-Fidel/PortWINE. Provide, please, a comparison table of these two projects.

**Comment by loathingKernel** [comment]
I do not think it is up to the project to compare itself with other possibly similar projects. You can try both and see which is a better fit for you. Umu is not user-facing software anyways, it is meant to be used by other launchers to run games with proton in a consistent environment.

**Comment by muhammadyusuf-kurbonov** [comment]
I got it. Let me try. Thank you very much and good luck!
