### ISSUE TITLE
Suggestion for simplifying game installation and uninstallation in umu-launcher

### ISSUE THREAD

**Issue by RaulKong898** [Open-Wine-Components/ULWGL#223]
Hi,

I'm writing to suggest a simplification of the process of installing and uninstalling Windows games through umu-launcher. It would be extremely useful if you could implement a .sh file to automate the entire installation process, as well as a separate .sh file for uninstallation. The user could click on these files or enter them in the terminal to launch the desired process.

Here's how the installation script could work:

Selecting the game's executable file (.exe): The script should allow the user to choose the .exe file of the game they want to install.
Choosing the installation location: The user should be able to specify where they want to install the game.
Launching the installation menu: The script should automatically launch the game's installation menu, just like it would on Windows.
Creating the necessary files: After the installation is complete, the script should automatically create the following in the specified location:
The game files.
A .sh file to run the game.
A .sh file to uninstall the game.
The uninstall script should delete all previously installed game files, including the .sh files created during installation.

I believe this approach, with separate .sh files for installation and uninstallation, would provide a much more familiar and simpler experience for users accustomed to Windows. It would also eliminate the need to go through complicated steps and reduce the risk of errors.

Thank you for your attention and I hope you will consider my suggestion!

**Comment by GloriousEggroll** [comment]
ideally umu should be used as a background tool for setting up the wine prefix and the installation of the game inside the prefix. It's the job of whatever parent application (lutris, heroic, faugus, junk store, etc) to perform external installation and cleanup of anything outside of the prefix including removal of the prefix itself

It seems alot of people keep misunderstanding this point. umu is a CLI tool meant to be used in tandem with user-friendly GUI applications. Yes it -can- be run solo but that's not the purpose of it.
