### ISSUE TITLE
Various virus scanning engines reporting steam.exe as malicious

### ISSUE THREAD

**Issue by HubNotSpoke** [Open-Wine-Components/ULWGL#225]
Bitdefender quarantines the steam.exe file and running it against VirusTotal, multiple AV scanning engines report it as malicious.

https://www.virustotal.com/gui/file/f96314240d426b4fd552b5b414cfa812327001f89064ea5677b4c3e950ae77d7

ClamAV does not detect it as malicious but I found that ClamAV is a bit lacking, thus why I started using Bitdefender.  If you are modifying the steam.exe and the malicious scan is a result of that modification, you need to post a disclaimer about it.

I can download the SteamSetup.exe for Windows from Steam's site, extract the Steam.exe, then rename it to steam.exe and put it where the quarantined file would be located and I have no issues running a game with the UMU runner and the file scans clean.  This applies to the regular GloriusEggroll Proton version as well.

Thank you all for the hard work that you do as you have allowed me to play many games that neither Wine nor Steam's Proton have allowed me to play over the years, but in this day and age of so many company security breaches, we need to be ever vigilant on addressing things at risk.

**Comment by GloriousEggroll** [comment]
? we don't ship steam.exe anywhere in umu. You are posting on the wrong bug tracker

If this is about proton please note that this is a false positive. The steam.exe built with proton comes directly from the steam helper code included in proton: https://github.com/GloriousEggroll/proton-ge-custom/tree/master/steam_helper
Proton's steam.exe is NOT the same as the full windows steam.exe. It is a bridge client that allows the windows functionality to work in linux.
