### ISSUE TITLE
How do I install this from .deb?

### ISSUE THREAD

**Issue by IfGremlinThen** [Open-Wine-Components/ULWGL#231]
I download `umu-launcher_1.1.2-1_all.deb`, and it says it says it needs dependency `python3-umu-launcher (= 1.1.2-1)`.

I download `python3-umu-launcher_1.1.2-1_all.deb`, and it says it needs dependency `python3-xlib (>= 0.33)`.

I follow the instructions to run `pip3 install python3-xlib` and it says:

```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python3-xlib in ./.local/lib/python3.10/site-packages (0.15)
```

Everything seems to suggest that I have this package already, but it is not installed globally and *I should not install it globally, but rather run it in a python environment* and at that point you lost me and I don't even know what the point of providing a .deb package is if I can't just use it to install it directly with my package manager. :/

**Comment by GloriousEggroll** [comment]
`dpkg -i python3-umu-launcher_1.1.2-1_all.deb`
`dpkg -i umu-launcher_1.1.2-1_all.deb`

python3-xlib is already a dependency and should get auto-pulled in when trying to install.

pip is not the way to install systemwide python packages, thats only for local python projects. system python packages come from your distro the same way other packages do.

FWIW I've also already verified the deb packages install and run on a clean version of ubuntu 24.04, and the upcoming release also works on debian 12

If you need debian 12 deb files download them from the artifacts here:
https://github.com/Open-Wine-Components/umu-launcher/actions/runs/11333870357/artifacts/2054816738

**Comment by IfGremlinThen** [comment]
It looks like my distro (Linux Mint) does not have an updated `python3-xlib` in it's repo.

**Comment by RobinFrcd** [comment]
Same for [Ubuntu 22.04](https://packages.ubuntu.com/jammy/python3-xlib) that's still on 0.29-1
