### ISSUE TITLE
[NixOS] 32-bit games crash with wrong ELF class: ELFCLASS64 error

### ISSUE THREAD

**Issue by ProspectPyxis** [Open-Wine-Components/ULWGL#246]
It seems 32-bit games crash immediately for me with the following error logs:

```
libGL error: MESA-LOADER: failed to open iris: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri/iris_dri.so: wrong ELF class: ELFCLASS64 (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri/iris_dri.so: wrong ELF class: ELFCLASS64 (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri/swrast_dri.so: wrong ELF class: ELFCLASS64 (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  469
  Current serial number in output stream:  468
```

This may be a user error, but if so, how would I fix this? I'm not sure if being on NixOS matters here.

I'm using the latest git build.

**Comment by R1kaB3rN** [comment]
You fix this by installing the relevant 32-bit driver packages provided by your distribution. See https://github.com/Open-Wine-Components/umu-launcher/issues/211 for related issue.

The container framework assumes an FHS-compliant filesystem and if it can’t find them for some reason, one way is to extend LD_LIBRARY_PATH with paths to the graphics driver files.

**Comment by ProspectPyxis** [comment]
Hm, this doesn't seem to work. I have 32-bit drivers enabled, and they are installed in `/run/opengl-driver-32/lib/dri` on NixOS, but adding `LD_LIBRARY_PATH=/run/opengl-driver-32/lib/dri:$LD_LIBRARY_PATH` didn't fix this issue - same error, including the search paths.

**Comment by R1kaB3rN** [comment]
cc @beh-10257 for insight

**Comment by bohanubis** [comment]
I'm still trying to fix this
(I have tests for university thats why I still can't find the bug)
https://github.com/Open-Wine-Components/umu-launcher/pull/241#issuecomment-2421588388

in the meantime
any 32 bit games recommendations

**Comment by ProspectPyxis** [comment]
I first ran into this issue with osu! stable. You can see my attempt to make a package for it here:

https://github.com/ProspectPyxis/nix-gaming/blob/fff7e770f1eb19db3f22e09040a29747316a8cc0/pkgs/osu-stable/default.nix

The installation works, but the game crashes right after the logo splash.

**Comment by bohanubis** [comment]
I guess the problem is that there is an imcompatibility between `pressure-vessel-wrap` and nixpkgs maybe a glibc update or something
(maybe next steam-runtime gonna fix this ??)
anyway installing osu

**Comment by GloriousEggroll** [comment]
the wrong elf class errors are not the problem. 

both 32 and 64 bit library paths are passed in the environment to pressure vessel. it tries all of them, therefore of course 64 bit libraries wont work for a 32 bit game. if the 32 bit libraries are present they will work. You still will get the wrong elf class errors because as I mentioned, it tries -all- of them. 

The LD_LIBRARY_PATH may look something like this as an example:

LD_LIBRARY_PATH=/path/to/64bit/libraries:/path/to/32bit/libraries

As you can see, they are passed together as one group with paths separated by ":", if the first path's libraries fails it reports the elf class errors and tries the second path and so on and so on.

You need to make sure the 32 bit mesa drivers are installed on the system. if in flatpak you need the mesa GL32 runtime.

**Comment by bohanubis** [comment]
I mean it doesn't work with regular wine ??
it this really an umu issue
![image](https://github.com/user-attachments/assets/24bdda2a-6d83-4f0f-a008-05a22aed6b51)

same exact issue using wine
maybe an older proton version
IDK TBH 
anyway yes
I'll give an update if I find anything interesting

**Comment by bohanubis** [comment]
![image](https://github.com/user-attachments/assets/baed3bff-cd76-46fb-877a-42f42f0ae850)
so I did another wine prefix yeah this is probably an issue with wine itself ??
I'm not sure though I don't really have another pc with another distro or a stable distro so yeah

**Comment by bohanubis** [comment]
ohhhh this is not the same error sorry my bad

**Comment by bohanubis** [comment]
The installation works, but the game crashes right after the logo splash.

wait thats the same thing thats happening to me ??
same with wine as well
so this is indeed a wine issue I guess

**Comment by ProspectPyxis** [comment]
Huh, the fact that wine doesn't work is actually weird - for me, normal wine works fine, at least using `wineWowPackages.staging`.

Which wine package are you using?

**Comment by ProspectPyxis** [comment]
Also, in regards to LD_LIBRARY_PATH ordering:

As I mentioned, I do already have 32-bit drivers installed, and I've tried setting the paths manually via environment variable. The problem seems more like for some reason, the Nix installation of this package specifically, since regular Wine still works for me, is simply not acknowledging the existence of the 32-bit drivers at all, no matter which environment variable I give it.

I've made sure 32-bit drivers are *definitely* installed at `/run/opengl-driver-32/lib/dri`, but:

`LD_LIBRARY_PATH=/run/opengl-driver-32/lib/dri:$LD_LIBRARY_PATH` - no effect, everything crashes same as before with the same errors
`LIBGL_DRIVERS_PATH=/run/opengl-driver-32/lib/dri` - different error ("no such file or directory"), but same effect - crashes whenever drivers are requested

**Comment by bohanubis** [comment]
@ProspectPyxis what version of nixpkgs you are using ??

**Comment by bohanubis** [comment]
btw I use wineWowPackages.full
I'll try staging

**Comment by ProspectPyxis** [comment]
I'm currently on unstable.

**Comment by bohanubis** [comment]
yeah using staging wine is useless
if I can't get this working using regular wine
sorry can't reproduce

**Comment by ProspectPyxis** [comment]
Oh, welp, I just fixed my issue:

```patch
--- ./packaging/nix/umu-run.nix 2024-10-23 07:03:11.623798359 +0700
+++ ./packaging/nix/umu-run.nix.fixed   2024-10-23 07:03:04.092709649 +0700
@@ -5,6 +5,7 @@
   targetPkgs = pkgs: ([
     package
   ]);
+  multiArch = true;
   runScript = writeShellScript "umu-run-shell" ''
     ${package}/bin/umu "$@"
   '';
```

Turns out we were missing a single very important line that actually adds the 32-bit libraries to the FHS.

I can create a very quick pull request for this.

**Comment by bohanubis** [comment]
sorry couldn't help if I can't even get the game working feel free to make a pr

sorry for missing that option for this long lol

**Comment by bohanubis** [comment]
@ProspectPyxis 
actually do you have any idea why its not working
![image](https://github.com/user-attachments/assets/76d1de20-7197-4aaa-9af3-ece2dae3fe2d)

**Comment by ProspectPyxis** [comment]
I've never seen those errors before, but my guess is missing winetricks options.

https://github.com/ProspectPyxis/nix-gaming/blob/fff7e770f1eb19db3f22e09040a29747316a8cc0/pkgs/osu-stable/default.nix

`dotnet45` is probably the most important one here, but `gdiplus` and `meiryo` is also listed.

**Comment by bohanubis** [comment]
ok thanks will see

**Comment by bohanubis** [comment]
@ProspectPyxis btw I tried the winetricks stuff today
and yeah true they were missing lol
