### ISSUE TITLE
Lutris + umu does not work anymore 

### ISSUE THREAD

**Issue by MattiBRNDMR** [Open-Wine-Components/ULWGL#253]
Hello,

as of today, running EA-App (and any other application) through lutris does not work anymore. Log says:

 `Traceback (most recent call last):
  File "/usr/share/lutris/bin/lutris-wrapper", line 205, in <module>
    main()
  File "/usr/share/lutris/bin/lutris-wrapper", line 132, in main
    process_pid = subprocess.Popen(args).pid
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/matti/.local/share/lutris/runtime/umu/umu_run.py'`

Wine version is set to GE-Proton(Latest). Worked just fine last night.

Thank you in advance for looking at this
Matti

**Comment by mihailim** [comment]
Are you using a Debian-based distribution by any chance, e.g. Ubuntu? If so, does it work immediately after running the following command **as root** (!!!)?

```bash
apparmor_parser --remove /etc/apparmor.d/bwrap-userns-restrict-umu
```

(Note: That command unloads the newly added AppArmor profile and its effects do not persist after a reboot; if that was the issue, then to make it persistent until a proper workaround is found you'll need to remove the `/etc/apparmor.d/bwrap-userns-restrict-umu` symlink.)

**Comment by mihailim** [comment]
Alternatively, please check if the file `/home/matti/.local/share/lutris/runtime/umu/umu_run` is marked as executable, and/or try

```bash
chmod +x /home/matti/.local/share/lutris/runtime/umu/umu_run
```

**Comment by MattiBRNDMR** [comment]
> Alternatively, please check if the file `/home/matti/.local/share/lutris/runtime/umu/umu_run` is marked as executable, and/or try
> 
> ```shell
> chmod +x /home/matti/.local/share/lutris/runtime/umu/umu_run
> ```

Hey, thank you! I am on CachyOS - marking this file as executable did the trick for me. Im not sure why it just stopped working though, as far as I know I did not install updates regarding lutris.

**Comment by mihailim** [comment]
The umu runtime updates itself when launching any Wine application using it as a runner unless the environment variable `UMU_RUNTIME_UPDATE` is defined with the value `0`, and maybe something went wrong there.

**Comment by GamertechAU** [comment]
It's the same with Heroic. The 1.1.3 update to umu-run.py doesn't have the executable flag so the apps can't run it.

You've got it fixed but for anyone else with the issue: Browse to the umu-run.py location, open the file properties for it and tick the executable checkbox. Lutris/Heroic/etc should load umu fine after that.

**Comment by mihailim** [comment]
Probably best to mark `umu_run` as executable and not `umu_run.py`, since `umu_run.py` is a symlink to the actual executable `umu_run`.

**Comment by GamertechAU** [comment]
The update also replaced the symlink with a copy of umu-run. So both files are now identical.

While apps are still using umu-run.py, that's the correct file to edit.

**Comment by mihailim** [comment]
Oh! Weird, for me it's still a symlink :)
