### ISSUE TITLE
error install umu-launcher for rpm fedora 41 beta

### ISSUE THREAD

**Issue by RaulKong898** [Open-Wine-Components/ULWGL#256]
Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - nothing provides python(abi) = 3.12 needed by umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch from @commandline
  - nothing provides python3.12dist(filelock) >= 3.9 needed by umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch from @commandline
  - nothing provides python3.12dist(python-xlib) >= 0.33 needed by umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch from @commandline

**Comment by R1kaB3rN** [comment]
Do you mind providing more details such as the commands you used to build the RPM?

Fedora 41 just officially released today, and while I have little experience with the Fedora distribution and `dnf`, I had the chance to test building our RPM package via `distrobox`. However, after my testing, I cannot reproduce your build errors after roughly following the instructions listed in our README through these steps:

1. `distrobox create -i fedora:41`
2. `distrobox enter fedora-41`
3. `git clone https://github.com/Open-Wine-Components/umu-launcher.git`
4. `cd umu-launcher/packaging/rpm`
5. `sudo dnf install -y mock fedpkg`
6. `fedpkg --release f41 srpm`
7. `mock -r /etc/mock/fedora-41-x86_64.cfg --rebuild --enable-network umu-launcher-1.1.3-1.20241029.51db530.fc41.src.rpm`
9. `cp -rv /var/lib/mock/fedora-41-x86_64/result .`
10. `cd result`
11. `sudo dnf install -y umu-launcher*.rpm`

**Comment by matias49** [comment]
I think the request was more to provide a release compatible with Fedora 41. The 1.1.3 Fedora-40 RPM release gives me the same error.

```
LANGUAGE=en sudo rpm -i umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch.rpm
error: Failed dependencies:
        python(abi) = 3.12 is needed by umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch
        python3.12dist(filelock) >= 3.9 is needed by umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch
        python3.12dist(python-xlib) >= 0.33 is needed by umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch
```

Thanks in advance

**Comment by dannyglover** [comment]
I'm also having this issue:

```
Failed to resolve the transaction:
Problem: conflicting requests
  - nothing provides python(abi) = 3.12 needed by umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch from @commandline
  - nothing provides python3.12dist(filelock) >= 3.9 needed by umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch from @commandline
  - nothing provides python3.12dist(python-xlib) >= 0.33 needed by umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch from @commandline
```

**Comment by Tiagoquix** [comment]
Same issue here on F41:
```
$ sudo dnf install umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch.rpm
[...]
Failed to resolve the transaction:
Problem: conflicting requests
  - nothing provides python(abi) = 3.12 needed by umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch from @commandline
  - nothing provides python3.12dist(filelock) >= 3.9 needed by umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch from @commandline
  - nothing provides python3.12dist(python-xlib) >= 0.33 needed by umu-launcher-1.1.3-1.20241023.8bc37bb.fc40.noarch from @commandline
[...]
```

**Comment by GloriousEggroll** [comment]
guys the rpm is built for f40. a new rpm needs to be built for f41. the dependency issues are because it was built on f40.

**Comment by korewaChino** [comment]
The RPM is built for Fedora 40, which has Python 3.12.

[Terra](https://terra.fyralabs.com) has a build for Fedora 41 and newer [here](https://github.com/terrapkg/packages/tree/frawhide/anda/games/umu).

**Comment by GloriousEggroll** [comment]
resolved:
https://github.com/Open-Wine-Components/umu-launcher/commit/304b5bd93192aa7b19d0bf82becee823aeebe391
https://github.com/Open-Wine-Components/umu-launcher/commit/90352466d502c40e147cfd11a428dde6c2899ab3
