### ISSUE TITLE
how to launch it?

### ISSUE THREAD

**Issue by Talion117** [Open-Wine-Components/ULWGL#260]
it seems the error i had before was fixed, thanks.

was able to install it.

how do i launch it?

**Comment by R1kaB3rN** [comment]
Here’s a more simple example than the one provided in our README:
`GAMEID=umu-0 umu-run winecfg`

Everything after `umu-run` should be your game and will run inside the Steam Runtime. See umu(1) for more example usages. Or if you prefer videos, watch  GloriousEggroll’s recent talk online at Ubuntu Summit 2024

**Comment by Talion117** [comment]
> Here’s a more simple example than the one provided in our README: `GAMEID=umu-0 umu-run winecfg`
> 
> Everything after `umu-run` should be your game and will run inside the Steam Runtime. See umu(1) for more example usages. Or if you prefer videos, watch GloriousEggroll’s recent talk online at Ubuntu Summit 2024

thanks.

**Comment by Talion117** [comment]
> Here’s a more simple example than the one provided in our README: `GAMEID=umu-0 umu-run winecfg`
> 
> Everything after `umu-run` should be your game and will run inside the Steam Runtime. See umu(1) for more example usages. Or if you prefer videos, watch GloriousEggroll’s recent talk online at Ubuntu Summit 2024

tried finding a app thinking it was a launcher. also. how to uninstall python3-umu-launcher_1.1.3-1_amd64.deb or umu-launcher_1.1.3-1_all.deb?

i accidently installed both.

**Comment by Talion117** [comment]
to install a game through lutris? with umu?
