### ISSUE TITLE
[NixOS] undefined symbol: __libc_pthread_init with multiArch active

### ISSUE THREAD

**Issue by piotr152** [Open-Wine-Components/ULWGL#261]
Hi there,

I recently stumbled upon an error on NixOS that seems to have been introduced by the addition of the multiArch linein in umu-run.nix in #252. Out of curiosity, I tried to install Notepad++ from here: https://notepad-plus-plus.org/downloads/v8.7/, both the 32bit and 64bit Version.

Here's my config file:

```toml
[umu]
prefix = "./prefixes/notepadpp/"
exe = "./npp.8.7.Installer.exe"
proton = "./proton/UMU-Proton-9.0-3.2/"
```

And here's the error I encountered.

```bash
/home/thatsme/umu/proton/UMU-Proton-9.0-3.2/files/bin/wine: symbol lookup error: /lib/i386-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
```

Removing `multiArch = true` fixes the issue. I was able to install Notepad++ and afterwards run the installed NP++ Executable with `multiArch` back on.

Using GE-Proton made no difference.

I tried to add glibc to targetPkgs and multiPkgs but that wasn't the solution.

I haven't looked much further to find out if this issue affects any games but this might be something worth looking into.

All the best and thank you for your amazing work!

**Comment by R1kaB3rN** [comment]
cc @beh-10257 for insight.

**Comment by bohanubis** [comment]
I will look into this at Saturday really sorry this is exams week
if you find anything though feel free to mention me

**Comment by bohanubis** [comment]
actually no I wasn't able to reproduce this sadly lol
I will ask another user to try to reproduce this
in the meantime what version of nixpkgs are you on ??

**Comment by Star-veil** [comment]
That's me, hi :)
Using unstable nixpkgs, the umu flake, clean wineprefix and with no specific proton I get it working with no issues on both x86 and x64.

**Comment by piotr152** [comment]
Well what can I say... I tried it out on another laptop and it worked. Seems like a me-problem then. Thank for having a look at it and sorry for the noise :heart:

**Comment by bohanubis** [comment]
@piotr152 

Actually when you find out what's the me problem

Mention it here
And thanks

**Comment by piotr152** [comment]
Okay, either the newest version or the fact that I removed my ages old ~/.local/share/Steam directory did the trick. I did both at the same time, so I can't say anything more specific.
