### ISSUE TITLE
Launch two applications on the same session and/or container using umu

### ISSUE THREAD

**Issue by redirectto** [Open-Wine-Components/ULWGL#263]
I’d like to ask if it’s possible to launch a second application within pressure-vessel, such as thprac or CE, using a command.
I’ve tried running the command `.../umu_run.py .../secondapp.exe`, but it didn’t work as expected.
Strangely, the second program actually launched **after** I closed the game.

For context:
- I’m using umu through Lutris (GE-Proton 9.16)
- I’ve managed to run the command using a pre-run script which includes additional code.
- The script waits for the game to launch, executes specific commands, and then waits for the game to close to run others.

Here’s the main command used in the script:
`sh -c "/home/deck/.var/app/net.lutris.Lutris/data/lutris/runtime/umu/umu_run.py /home/deck/.local/share/thprac/thprac.exe" &`

I’m also having this issue when launching non-Steam games directly from the Steam interface.
With Steam games from the store, this process actually works using a similar script.
By running the command `.../proton .../secondapp.exe` (ensuring that the same version of Proton used to launch the game is specified), I can get the second application to run concurrently but I'm not sure if they are on the same container and only works with Steam games from the store.

Any guidance on getting the second application to run simultaneously with the game would be greatly appreciated.

**Comment by mactan-sc** [comment]
https://github.com/Open-Wine-Components/umu-launcher/wiki/Frequently-asked-questions-(FAQ)#how-do-i-run-more-than-one-game-in-the-same-wine-prefix

**Comment by R1kaB3rN** [comment]
Yes, it’s possible. Please read the project’s wiki for more details. Also any issues you have with Steam besides the window management we do to support Steam Mode is outside this project’s scope, so, in the future, please do not include those issues in your report.
