### ISSUE TITLE
umu-run hangs for long time waiting to connect to repo.steampowered.com

### ISSUE THREAD

**Issue by eskay993** [Open-Wine-Components/ULWGL#264]
Today I noticed umu-run hangs for 1 min when run, followed by:

```
WARNING: repo.steampowered.com returned the status: 504
````
and then it carries on it's merry way. 

If I disable my network, umu runs quickly (following an expected name resolution error due to no internet).

I imagine the timeout is set to 1 min? If that's the case, I wonder if this is could be much shorter? Most people (myself included) would force quit thinking something has gone wrong waiting that long. Just flagging as thought.

Many thanks.

**Comment by R1kaB3rN** [comment]
Thanks for reporting this.

Yes, I already have a solution that should decisively address any network-related errors, as I'm observing some users may not have the best internet connectivity or have problems connecting to _repo.steampowered.com_ for some reason when umu-launcher attempts to update the runtime on launch. However, it won't be merged in the short term as the focus right now for the next few days/weeks (or at least when most Lutris users can properly run their games) will be on bug fixes, excluding the network-related errors ones such as yours.

Until then, as a workaround, set `UMU_RUNTIME_UPDATE=0` to disable the runtime updates.
