### ISSUE TITLE
LibGL Vulkan Loader wrong ELF class: ELFCLASS64 and installs/uses wrong drivers on specific host operating systems (flatpak)

### ISSUE THREAD

**Issue by ckupe** [Open-Wine-Components/ULWGL#268]
**Issue:**
When running umu-run from inside a flatpak, using Proton-GE 9.18, LibGL errors are thrown from within the steam linux runtime container, and the wrong drivers are being used.

**Expected Behavior:**
GL32 drivers should be installed and used with the flatpak, and vulkan-loader + steam runtime container (pressure-vessel) should be loading the appropriate architecture driver (in this case, 32 bit over 64 bit).

**Occurs on:**
This occurs on Arch linux and Fedora 41 on two different desktop machines with Nvidia GPUs running nvidia-open 565.57.1-2, as well as an Intel Iris based Lenovo T14s laptop.

**Does not occur on:**
This issue does not occur if host operating system is installed as Bazzite 41 on both Nvidia and Intel Iris based machines.

- Bazzite already has flathub repo installed in `user` scope as `flathub`, but Fedora41 and Arch do not, and usually configure `flathub` repo for `system`.

Nvidia 565.57.1-2 Desktop (Arch):
![image](https://github.com/user-attachments/assets/e2873e92-00e7-4308-9f4d-3c0d22c42e1d)

Intel Iris Lenovo T14s (Fedora 41):
```bash
Proton: /home/ckupe/data/project-rk/drive_c/launcher/PRK.Launcher.exe
Proton: Executable a unix path, launching with /unix option.
fsync: up and running.
Command exited with status: 0
libGL error: MESA-LOADER: failed to open iris: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri/iris_dri.so: wrong ELF class: ELFCLASS64 (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri/swrast_dri.so: wrong ELF class: ELFCLASS64 (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  393
  Current serial number in output stream:  392
```

Test Host (Arch, Nvidia) info:

```
$ sudo pacman -Qs nvidia
local/egl-gbm 1.1.2-1
    The GBM EGL external platform library
local/egl-wayland 4:1.1.16-1
    EGLStream-based Wayland external platform
local/lib32-nvidia-utils 565.57.01-1
    NVIDIA drivers utilities (32-bit)
local/libvdpau 1.5-3
    Nvidia VDPAU library
local/nvidia-open 565.57.01-2
    NVIDIA open kernel modules
local/nvidia-utils 565.57.01-1
    NVIDIA drivers utilities
```

```
Proton: /home/me/.var/app/com.projectrk.launcher/data/project-rk/drive_c/launcher/PRK.Launcher.exe
Proton: Executable a unix path, launching with /unix option.
fsync: up and running.
Command exited with status: 0
libGL error: MESA-LOADER: failed to open nouveau: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri/nouveau_dri.so: wrong ELF class: ELFCLASS64 (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: nouveau
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri/swrast_dri.so: wrong ELF class: ELFCLASS64 (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  385
  Current serial number in output stream:  384
  ```
  `initrd=\initramfs-linux.img root=/dev/vg0/lv_root nvidia-drm.modeset=1`
  `6.11.6-arch1-1`

```
  $ sudo cat /sys/module/nvidia_drm/parameters/fbdev

Y
```

```
$ flatpak --gl-drivers
nvidia-565-57-01
default
host
```

Arch-Nvidia system does not automatically install `org.freedesktop.Platform.GL32` extensions when flatpak is installed.
Intel-Fedora41 system's installed runtimes (fresh install):
```
ckupe@fedora:~/projectrk-flatpak$ flatpak list --runtime
Name                             Application ID                                           Version                              Branch                 Installation
Freedesktop Platform             org.freedesktop.Platform                                 freedesktop-sdk-23.08.25             23.08                  user
Mesa                             org.freedesktop.Platform.GL.default                      24.2.5                               23.08                  user
Mesa (Extra)                     org.freedesktop.Platform.GL.default                      24.2.5                               23.08-extra            user
Mesa                             org.freedesktop.Platform.GL.default                      24.2.5                               24.08                  system
Mesa (Extra)                     org.freedesktop.Platform.GL.default                      24.2.5                               24.08extra             system
Intel VAAPI driver               org.freedesktop.Platform.VAAPI.Intel                                                          23.08                  user
Intel VAAPI driver               org.freedesktop.Platform.VAAPI.Intel                                                          24.08                  system
openh264                         org.freedesktop.Platform.openh264                        2.1.0                                2.2.0                  user
openh264                         org.freedesktop.Platform.openh264                        2.4.1                                2.4.1                  system
Freedesktop SDK                  org.freedesktop.Sdk                                      freedesktop-sdk-23.08.25             23.08                  user
Freedesktop SDK                  org.freedesktop.Sdk                                      freedesktop-sdk-24.08.5              24.08                  system
i386                             org.freedesktop.Sdk.Compat.i386                                                               23.08                  user
toolchain-i386                   org.freedesktop.Sdk.Extension.toolchain-i386                                                  23.08                  user

```

**Comment by ckupe** [comment]
Flatpak build manifest found [here](https://github.com/ckupe/projectrk-flatpak)

**Comment by GloriousEggroll** [comment]
I dont know how many times I have to repeat this. ELFCLASS errors are NOT because of incorrect driver versions.

https://github.com/Open-Wine-Components/umu-launcher/issues/246#issuecomment-2429964828

yes, the problem is you are missing 32 bit driver versions due to 32 bit flatpak dependencies missing.
NO, ELFCLASS errors are NOT the problem, and this is NOT an UMU issue.

```
both 32 and 64 bit library paths are passed in the environment to pressure vessel. it tries all of them, therefore of course 64 bit libraries wont work for a 32 bit game. if the 32 bit libraries are present they will work. You still will get the wrong elf class errors because as I mentioned, it tries -all- of them.

The LD_LIBRARY_PATH may look something like this as an example:

LD_LIBRARY_PATH=/path/to/64bit/libraries:/path/to/32bit/libraries

As you can see, they are passed together as one group with paths separated by ":", if the first path's libraries fails it reports the elf class errors and tries the second path and so on and so on.

You need to make sure the 32 bit mesa drivers are installed on the system. if in flatpak you need the mesa GL32 runtime.
```

It bothers me to see so many people reporting ELFCLASS errors as actual errors. I will look into the flatpak (which isn't official yet btw) to see if we can make it add 32 bit mesa as a dependency. Just please be aware the ELFCLASS error is -not- an error. whatever umu or the game does -not- use will be reported as elfclass error, regardless even if both 64 and 32 bit are present.

**Comment by ckupe** [comment]
@GloriousEggroll the systems tested *did* have 32 bit drivers installed on the host- so why would the org.freedesktop.Platform.GL32 extensions not install as expected?

Both the Arch systems had the lib32_nvidia_utils packages installed and configured, with correctly regenerated ramdisks e.g. mkinitcpio

and the Fedora 41 install (on Lenovo w/ intel iris) had its respective i686 packages installed as well.

There's a discovery functionality broken here/inconsistent.

**Comment by GloriousEggroll** [comment]
if it's a 64 bit game, it's going to report 32 bit ELFCLASS errors. If it's a 32 bit game it's going to report 64 bit ELFCLASS errors. As mentioned it tries all of them within LD_LIBRARY_PATH

**Comment by GloriousEggroll** [comment]
Just to clarify, inside flatpak you need:

org.freedesktop.Platform.GL.default
org.freedesktop.Platform.GL32.default

and they must be the version the application expects:
```
runtime-version: &runtime-version '23.08'
```

Outside of flatpak, you need 32 and 64 bit mesa packages.

If you are on nvidia you need the equivalent both inside and outside flatpak

also -- sorry to snap at the ELFCLASS errors. I'm just tired of them being reported when they are not the problem.

**Comment by ckupe** [comment]
Intel Iris (mesa) system:
```
x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so not found, ignoring: Missing dependencies: Could not find "libigdgmm.so.12" in LD_LIBRARY_PATH "", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
pressure-vessel-wrap[8]: W: Using libGLX_mesa.so.0 from provider system for some but not all architectures! Will take /usr/share/drirc.d from provider.

```

On the Arch Nvidia systems, they also had both the 32 bit and 64 bit drivers as well.

**Comment by ckupe** [comment]
I'm not saying it's necessarily an umu issue specifically, but a flatpak issue; I couldn't decide if I should have brought this issue into freedesktop/flatpak, or this repo, or the steam runtime repo.

I decided to report here since the extensions configs in the builder manifest *look* right, but when installing across different distros, it's not behaving as expected

**Comment by ckupe** [comment]
This is related to https://github.com/flatpak/flatpak/issues/3072

The issue is, `org.freedesktop.Platform.GL32` is not a _runtime_ dependency, but used in this context (for umu-launcher) as an _application_ dependency. 

So GL gets installed, since it's in org.freedesktop.Platform, but not GL32 because it's not a dep in the runtime.

What I am still lost on is how flatpak itself handles discovery and boolean evaluation of things like `active-gl-driver` from the host's perspective- since these dependencies were correctly installing automatically (GL32) on bazzite, but not Fedora 41- all I can think is that bazzite OOTB has `flathub` registered at `user` scope by default, whereas arch has it configured for `system` as well as fedora 41- so building on those machines, and installing on those machines result in inconsistent behavior with automatically sourcing the GL32 bits.

Curious how this problem will be solved in the umu build manifest/user experience.

The behavior is also different depending if you're building locally (which creates a local repo, and org.freedesktop.Platform.GL32 will not be present in the local repo at build time, so it cannot be installed at the end of the build, with flags like `flatpak-builder --install ...` unless you also add `--install-deps-from=flathub` or an equivalent accessible named repo where the GL32 extension can be sourced from.

The linked issue tracks this discussion about unreliable dependency sourcing behavior for org.freedesktop.Platform.GL32 specifically.
