### ISSUE TITLE
Feature request: add command line options -v and --version to show version and exit

### ISSUE THREAD

**Issue by pickworthi** [Open-Wine-Components/ULWGL#272]
Its a small thing, but I think it would be useful to add the ability to print the version of umu-run in response to command line flags -v or --version.

I have prepared a pull request with changes that I tested, I'll link it here when I submit it.

**Comment by pickworthi** [comment]
Pull  request [273 here](https://github.com/Open-Wine-Components/umu-launcher/pull/273)

**Comment by R1kaB3rN** [comment]
Closing completed since https://github.com/Open-Wine-Components/umu-launcher/pull/273.
