### ISSUE TITLE
1.1.4 does not build on Nix

### ISSUE THREAD

**Issue by dinckelman** [Open-Wine-Components/ULWGL#296]
Derivation logs:

```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/nxqcg590rwak6h2s8xls24xalhrj8qmp-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/umu/umu_util.py
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
patching script interpreter paths in ./configure.sh
./configure.sh: interpreter directive changed from "#!/usr/bin/env bash" to "/nix/store/0irlcqx2n3qm6b1pc9rsd2i8qpvcccaj-bash-5.2p37/bin/bash"
configure flags: --prefix=/nix/store/9q2i9svkiqc7kf90r14vwvdq3skl7v2x-python3.12-umu-launcher-1.1.4 --prefix=/nix/store/9q2i9svkiqc7kf90r14vwvdq3skl7v2x-python3.12-umu-launcher-1.1.4
:: Created ./Makefile, now run "make" to build.
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
build flags: SHELL=/nix/store/0irlcqx2n3qm6b1pc9rsd2i8qpvcccaj-bash-5.2p37/bin/bash PYTHON_INTERPRETER=/nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7/bin/python SHELL_INTERPRETER=/run/current-system/sw/bin/bash DESTDIR=/nix/store/9q2i9svkiqc7kf90r14vwvdq3skl7v2x-python3.12-umu-launcher-1.1.4
fatal: not a git repository (or any of the parent directories): .git
:: Building umu 
/nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7/bin/python -m build --wheel --skip-dependency-check --no-isolation --outdir=builddir
* Building wheel...
Successfully built umu_launcher-1.1.4-py3-none-any.whl
touch builddir/.build-umu-dist
:: Building umu man pages 
scdoc < docs/umu.1.scd > builddir/umu.1
scdoc < docs/umu.5.scd > builddir/umu.5
touch builddir/.build-umu-docs
:: Building umu-launcher 
sed 's|##INSTALL_PATH##|/nix/store/9q2i9svkiqc7kf90r14vwvdq3skl7v2x-python3.12-umu-launcher-1.1.4/bin/umu-run|g' umu/umu-launcher/umu-run.in > builddir/umu-launcher-run
touch builddir/.build-umu-launcher
:: Building vendored dependencies 
python3 -m pip install urllib3 -t builddir
/nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7/bin/python3: No module named pip
make: *** [Makefile.in:104: builddir/.build-umu-vendored] Error 1
```

**Comment by R1kaB3rN** [comment]
Pip will be a new build dependency as we're vendoring urllib3 version 2. However, if I'm not mistaken, NixOS may package so it may be possible for users to just use the native package instead of our vendored one. cc @beh-10257 for insight about that.

**Comment by R1kaB3rN** [comment]
I don't use NixOS so I cannot confirm this. But to get the build working, I believe you just need to simply add the pip package to the `depsBuildBuild` list. See: https://github.com/Open-Wine-Components/umu-launcher/blob/c382bf88c486ded9cef1c313bc318bfadd506a52/packaging/nix/umu-launcher.nix#L14

**Comment by bohanubis** [comment]
hello @R1kaB3rN I mean urllib3 is already packaged on nixpkgs https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=urllib3

can't the build process detect that its already installed ??

**Comment by bohanubis** [comment]
yeah nix doesn't like the fact that it wants to connect to internet I guess ??
![image](https://github.com/user-attachments/assets/2928ae28-4867-4f1d-adaa-ec6039f8c019)

what is vendored in the first place is it another package or what if I package vendored will the buid process detect it ??

as a side note I'm going to sleep and tomorrow I have a competition so I will only start working on this again in IDK 14 hours
also yes if there is a way to make it so you can detect if urllib3 is already in the environment and not use pip if it is that would make my life soooo much easier and thanks

**Comment by R1kaB3rN** [comment]
> hello @R1kaB3rN I mean urllib3 is already packaged on nixpkgs https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=urllib3

If v2 is already on NixOS, just simply delete the `_vendor` directory within our module's directory and add pip as a build dependency. Once that's done, umu-launcher should still be able to find it in NixOS's `PYTHONPATH` as we don't use relative imports. Right now, we're vendoring it by default [as most distros do not package the latest version of it](https://repology.org/project/python%3Aurllib3/versions). Doing it this way will lead to the least amount of trouble for the majority.

> can't the build process detect that its already installed ??

It's possible, but I don't believe adding custom detection logic or hooks would be the right way to go about this.

**Comment by bohanubis** [comment]
I mean nixos packages latest version I guess https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/python-modules/urllib3/default.nix#L26
also where is the _vendor directory you are talking about
I don't even see a module directory

**Comment by LovingMelody** [comment]
I see this line in the Makefile, which I believe is whats doing this https://github.com/Open-Wine-Components/umu-launcher/blob/3277b47c9f87ecf736e1df7ed65cc0e25466f9b2/Makefile.in#L102-L104

We can probably patch the Makefile or export the urllib3 form nix to `builddir` if I'm understanding what's happening correctly

**Comment by LovingMelody** [comment]
Submitted a quick PR, there's probably another way to fix it.

**Comment by R1kaB3rN** [comment]
Thanks @LovingMelody for the PR :smile:. I think it's fine for now.

To follow up on that, do you know how one can add [truststore](https://github.com/sethmlarson/truststore) as an optional dependency for the Flake besides adding it to `propogatedBuildInputs`? 

[I have PR open for it here](https://github.com/Open-Wine-Components/umu-launcher/pull/298). If there's a better way let me know/send a patch. I'll try to merge it ASAP.

**Comment by bohanubis** [comment]
why would you want it to be optional ??

I can think of a way so users will do something like this

umu.override (truststore = true);

is that what is wanted can the project built without truststore
