### ISSUE TITLE
The latest update says "fix runtime path in snap", but where IS the Snap package? 

### ISSUE THREAD

**Issue by vrement** [Open-Wine-Components/ULWGL#299]
Searching in Snapcraft Snap Store yields no results. What am i missing here? Where is the Snap package?

https://snapcraft.io/store?q=umu-launcher

**Comment by R1kaB3rN** [comment]
umu-launcher isn't published in the Snapcraft store and it probably won't, so [users need to build it themselves by following our instructions](https://github.com/Open-Wine-Components/umu-launcher/tree/main/packaging/snap#notice). However, in the future, we can streamline this a bit so users don't have to build it themselves by automating the Snap build then attaching the *.snap file as a Github release asset.

**Comment by vrement** [comment]
> [users need to build it themselves by following our instructions](https://github.com/Open-Wine-Components/umu-launcher/tree/main/packaging/snap#notice)

I'm confused then. What is the point of a snap package if it must be built by users themselves via difficult instructions? The effort is similar to building from source. What's with this decision that people have to build their packages themselves?
