### ISSUE TITLE
Don't create prefix files/folders when UMU_NO_PROTON is used.

### ISSUE THREAD

**Issue by CcMenta** [Open-Wine-Components/ULWGL#301]
Linux native games have no use for prefixes and it is annoying that a programs create files/folders that they don't even use so it would be great if folder doesn't exist and `UMU_NO_PROTON=1` launch argument is used to not create a prefix.

**Comment by R1kaB3rN** [comment]
Thanks for reporting this, and I agree with you. Right now, I have a PR open that addresses this.
