### ISSUE TITLE
(Question) Is umu being developed strictly for games, or could other software be supported as well?

### ISSUE THREAD

**Issue by kawa-sanmyaku** [Open-Wine-Components/ULWGL#304]
Hello, very interested in the development of umu-launcher but I'd also like to run non-game software like the Affinity suite for graphic design, this software in particular requires a specific fork of Wine by ElementalWarrior that has some fixes for it to work _kind of_ but unfortunately the programs freeze when I copy-paste between documents :(

So I'm looking at umu-launcher as a potential alternative, I'll test later tonight if it happens to run Affinity as-is, but my question is, is umu-launcher only planned for games or would you include support for some other non-game Windows software?

If I can get it to work for at least 1 hour without crashing I can finally delete the Window ^-^

**Comment by R1kaB3rN** [comment]
Good question, and this was actually [already asked by someone at Ubuntu Summit this year](https://youtu.be/byPpJW5l6pg?t=5666).

Yes, as a long term goal, we would like to look into extending support for running non-game Windows software too as we recognize umu's architecture can be reused to satisfy those use cases as well. Though, before supporting this I think we'll need to start [building and customizing the runtime](https://github.com/Open-Wine-Components/umu-launcher/issues/4) already as the two are related. For that use case, Proton will probably will not be used and only maybe a subset of its components (e.g., wine staging).

**Comment by R1kaB3rN** [comment]
Closing as completed and I ensured this request has been tracked.
