### ISSUE TITLE
What is the difference with runinprefix and run proton verbs?

### ISSUE THREAD

**Issue by CcMenta** [Open-Wine-Components/ULWGL#307]
I use faugus launcher and what I noticed that when I give the launch argument `PROTON_VERB=runinprefix` modded stardew valley (windows) gives an error and doesn't launch while I don't give value for `PROTON_VERB` (default is `waitforexitandrun`) or use `run` instead of `runinprefix` works.
What is the difference.

Important to note when running the game with umu it works fine but running it with faugus has this issue and it works fine if I just simply type it out with the same umu-run file.

**Comment by R1kaB3rN** [comment]
By default, Proton will automatically configure the WINE prefix each launch to ensure its in order and try to setup game drive for the title. The setup also occurs when the run verb is set, but minus the call to the wineserver binary before running the game through WINE. Both verbs, waitforexitandrun and run, can also result in different command line arguments (e.g., wine64 binary is explicitly used). Without going into the details on Proton’s prefix setup though, defaulting to skipping it by using a verb like runinprefix can lead to various consequences so it’s recommended for users/clients to use a verb that enables its setup. For more details and if you’re really interested, I encourage you to look into [proton’s source code](https://github.com/GloriousEggroll/proton-ge-custom/blob/master/proton).
