### ISSUE TITLE
Umu ignores proton Environment variables?

### ISSUE THREAD

**Issue by jienma** [Open-Wine-Components/ULWGL#316]
Hey,
I was wondering - maybe I'm wrong:
Does umu ignore proton env variables?

It seems like it doesn't use the env variables I exported.
For example:
export PROTON_NO_D3D12=1
(The game still launches with DX12 for some reason)

OS: Ubuntu
Command Example:
    GAMEID="${GAMEID}" \
    PROTONPATH="${PROTON_DIR}" \
    ${CURRENT_DIR}/umu/umu-run explorer.exe /desktop=Lyra,1920x1080 "${EXECUTABLE_PATH}" &>>${CURRENT_DIR}/proton.log

**Comment by R1kaB3rN** [comment]
No, for the most part, umu respects Proton’s environment variables. In fact, it never removes environment variables and you can safely assume that all of Proton’s envvar are applicable. For instance, if you set PROTON_LOG=1, a file should be created at $HOME like you would expect. 

However, there are some environment variables that are private and umu will modify some of them so users can run their game. PROTON_NO_D3D12 is not one them though. 

For more details, see https://github.com/Open-Wine-Components/umu-launcher/blob/6189d0d9fd062e89a375db20aeae1d1c009e9833/umu/umu_run.py#L750

**Comment by R1kaB3rN** [comment]
Additionally, for more info, you can set UMU_LOG=1 to see what umu exactly sets at runtime for the game.

**Comment by R1kaB3rN** [comment]
Also, whether a Proton environment variable will have any effect depends on the Proton build’s version as some can be obsolete. 

Besides Proton and umu, other components that may affect environment variables is protonfixes and Pressure Vessel.
