### ISSUE TITLE
Use stderr for logging 

### ISSUE THREAD

**Issue by imLinguin** [Open-Wine-Components/ULWGL#34]
Instead of a plain print statement we should make sure we log stuff into stderr. Launchers may read the stdout, for functionality like cloud saves etc...

**Comment by loathingKernel** [comment]
I support this way of doing logging to `stderr` and I like that this is an open issue now to be used as reference in the future.

Yesterday with @R1kaB3rN we improved the situation a bit through https://github.com/Open-Wine-Components/ULWGL-launcher/commit/a7c38855bc66df81f13d9841ef54d87e7120d341 and https://github.com/Open-Wine-Components/ULWGL-launcher/commit/ffd22ca1a14e2ab999b9470ed7011d3d5a4b2fce. The one offense that remains right now is [here](https://github.com/Open-Wine-Components/ULWGL-launcher/blob/main/ulwgl_run.py#L130)

**Comment by bziemons** [comment]
I would suggest to use the [python logging module](https://docs.python.org/3/library/logging.html) instead. It logs to stderr by default and has useful mechanisms like log levels.
