### ISSUE TITLE
Runner using libs not available in Python < 3.11 causing `ModuleNotFoundError`

### ISSUE THREAD

**Issue by zocker-160** [Open-Wine-Components/ULWGL#37]
`ulwgl_run.py` is using 
https://github.com/Open-Wine-Components/ULWGL-launcher/blob/33bd82851aba4106851523cd952511ead0057da2/ulwgl_run.py#L9

which is not part of the Python stdlib [prior to 3.11](https://docs.python.org/3/library/tomllib.html).
```
  File "/home/zocker/testing/runtime/ULWGL-launcher/ulwgl-run", line 9, in <module>
    import tomllib
ModuleNotFoundError: No module named 'tomllib'
```
Ubuntu 22.04 is shipping Python 3.10 by default.

**Comment by GloriousEggroll** [comment]
@R1kaB3rN
