### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FeyrisTan** [Open-Wine-Components/ULWGL#49]
I'm getting this error:

`Traceback (most recent call last): File "/usr/bin/ulwgl-run", line 317, in <module> sys.exit(main()) ^^^^^^ File "/usr/bin/ulwgl-run", line 290, in main setup_ulwgl(root, local) File "/usr/share/ULWGL/ulwgl_util.py", line 181, in setup_ulwgl return _update_ulwgl(root, local, steam_compat, json, _get_json(local, CONFIG)) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/share/ULWGL/ulwgl_util.py", line 408, in _get_json json = load(file) ^^^^^^^^^^ File "/usr/lib/python3.11/json/__init__.py", line 293, in load return loads(fp.read(), ^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/json/__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by R1kaB3rN** [comment]
Hello, do you mind using the latest source to see if the issue still occurs? Thanks

**Comment by R1kaB3rN** [comment]
Closing until further notice as it should currently be fixed in main
