### ISSUE TITLE
Multiple Launch Feature?

### ISSUE THREAD

**Issue by cybik** [Open-Wine-Components/ULWGL#5]
Silly idea: could there be a "multiple launch options" feature? Similar to what Steam already does, but essentially for ULWGL entries, handled by ULWGL itself.

Example: let's say ULWGL-6384 aka Genshin Impact (Launcher), is in the database. A player could want to use the Google Play PC variant instead of the Standard Launcher for reasons all their own. In such a case, the ULWGL "profile" could fetch the appropriate installer, or fetch the generic installer and apply specific config.ini changes to make the local install into a Google Play PC-enabled install.

There could be multiple installer variants for other titles as well, I just have this example on hand.

**Comment by GloriousEggroll** [comment]
> Silly idea: could there be a "multiple launch options" feature? Similar to what Steam already does, but essentially for ULWGL entries, handled by ULWGL itself.
> 
> Example: let's say ULWGL-6384 aka Genshin Impact (Launcher), is in the database. A player could want to use the Google Play PC variant instead of the Standard Launcher for reasons all their own. In such a case, the ULWGL "profile" could fetch the appropriate installer, or fetch the generic installer and apply specific config.ini changes to make the local install into a Google Play PC-enabled install.
> 
> There could be multiple installer variants for other titles as well, I just have this example on hand.

ULWGL is not for fetching installers. that is the job of the parent application launching it.
ULWGL's only job is to apply protonfixes for the application being fed to it. It is -not- grabbing the application itself. This is why the ULWGL id  and the executable are required to be provided when using ulwgl
