### ISSUE TITLE
A launcher for our launchers that can be summed up by a commandline.

### ISSUE THREAD

**Issue by ghost** [Open-Wine-Components/ULWGL#58]
https://imgs.xkcd.com/comics/standards.png

Ban me, delete me, block me. I do not care. This isn't a solution to any problem. This is just a sidetrek off into some donkeyshow while you're already running the circus.

**Comment by imLinguin** [comment]
ULWGL is a solution for running Proton outside of Steam and without having Steam as dependency. If there is already any competing standard for this use case, please share it, I'd like to use it.

**Comment by strycore** [comment]
This coward deleted his Github account after realizing he was full of shit and he was dealing with the elite of Linux gaming when he hasn't provided any value to society ever.
