### ISSUE TITLE
Launch games without internet

### ISSUE THREAD

**Issue by Aqa-Ib** [Open-Wine-Components/ULWGL#60]
When not defining PROTONPATH, it is not possible to launch a game without an active internet connection.

Thank you so much for this wonderful project. Cheers !

**Comment by Aqa-Ib** [comment]
Maybe we could make a check like here ?
https://github.com/Open-Wine-Components/ULWGL-protonfixes/commit/7c1aac0bed43fbba36b0bbf2bb9eea2615076d46

**Comment by Aqa-Ib** [comment]
Hey, thanks for the commit ! However, still not working here:

Traceback (most recent call last):
  File "/usr/share/ulwgl/ulwgl_run.py", line 322, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/share/ulwgl/ulwgl_run.py", line 291, in main
    setup_ulwgl(root, local)
  File "/usr/share/ulwgl/ulwgl_util.py", line 152, in setup_ulwgl
    create_connection(("1.1.1.1", 80), timeout=1)
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

**Comment by Aqa-Ib** [comment]
Thanks for the commit @R1kaB3rN , much appreciated. However, still not working here.
If you want me to test some code, just say it.

Traceback (most recent call last):
File "/usr/share/ulwgl/ulwgl_run.py", line 322, in
sys.exit(main())
^^^^^^
File "/usr/share/ulwgl/ulwgl_run.py", line 291, in main
setup_ulwgl(root, local)
File "/usr/share/ulwgl/ulwgl_util.py", line 152, in setup_ulwgl
create_connection(("1.1.1.1", 80), timeout=1)
File "/usr/lib/python3.11/socket.py", line 851, in create_connection
raise exceptions[0]
File "/usr/lib/python3.11/socket.py", line 836, in create_connection
sock.connect(sa)
OSError: [Errno 101] Network is unreachable

**Comment by R1kaB3rN** [comment]
> Thanks for the commit @R1kaB3rN , much appreciated. However, still not working here. If you want me to test some code, just say it.
> 
> Traceback (most recent call last): File "/usr/share/ulwgl/ulwgl_run.py", line 322, in sys.exit(main()) ^^^^^^ File "/usr/share/ulwgl/ulwgl_run.py", line 291, in main setup_ulwgl(root, local) File "/usr/share/ulwgl/ulwgl_util.py", line 152, in setup_ulwgl create_connection(("1.1.1.1", 80), timeout=1) File "/usr/lib/python3.11/socket.py", line 851, in create_connection raise exceptions[0] File "/usr/lib/python3.11/socket.py", line 836, in create_connection sock.connect(sa) OSError: [Errno 101] Network is unreachable

Thanks for reporting this. I'll look into it once again and push a fix.

I could handle the OSError, which is straightforward. Though, unfortunately, I cannot reproduce this on my end even when turning off my network.

**Comment by Aqa-Ib** [comment]
Let me see what is going on.

**Comment by R1kaB3rN** [comment]
> Let me see what is going on.

Just made a PR that attempts to fix it. If you can, please try it out and post the stack trace again if there is one.

**Comment by Aqa-Ib** [comment]
Traceback (most recent call last):
  File "/usr/share/ulwgl/ulwgl_run.py", line 292, in main
    setup_ulwgl(root, local)
  File "/usr/share/ulwgl/ulwgl_util.py", line 152, in setup_ulwgl
    create_connection(("1.1.1.1", 80), timeout=1)
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/ulwgl/ulwgl_run.py", line 330, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/share/ulwgl/ulwgl_run.py", line 302, in main
    if e.error != ENETUNREACH:
       ^^^^^^^
AttributeError: 'OSError' object has no attribute 'error'

**Comment by R1kaB3rN** [comment]
> Traceback (most recent call last): File "/usr/share/ulwgl/ulwgl_run.py", line 292, in main setup_ulwgl(root, local) File "/usr/share/ulwgl/ulwgl_util.py", line 152, in setup_ulwgl create_connection(("1.1.1.1", 80), timeout=1) File "/usr/lib/python3.11/socket.py", line 851, in create_connection raise exceptions[0] File "/usr/lib/python3.11/socket.py", line 836, in create_connection sock.connect(sa) OSError: [Errno 101] Network is unreachable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/share/ulwgl/ulwgl_run.py", line 330, in sys.exit(main()) ^^^^^^ File "/usr/share/ulwgl/ulwgl_run.py", line 302, in main if e.error != ENETUNREACH: ^^^^^^^ AttributeError: 'OSError' object has no attribute 'error'

Sorry, error was a typo and I made the correction. https://github.com/Open-Wine-Components/ULWGL-launcher/pull/62

**Comment by Aqa-Ib** [comment]
Traceback (most recent call last):
  File "/usr/share/ulwgl/ulwgl_run.py", line 330, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/share/ulwgl/ulwgl_run.py", line 309, in main
    check_env(env)
  File "/usr/share/ulwgl/ulwgl_run.py", line 151, in check_env
    get_ulwgl_proton(env)
  File "/usr/share/ulwgl/ulwgl_dl_util.py", line 24, in get_ulwgl_proton
    files = _fetch_releases()
            ^^^^^^^^^^^^^^^^^
  File "/usr/share/ulwgl/ulwgl_dl_util.py", line 64, in _fetch_releases
    conn.request(
  File "/usr/lib/python3.11/http/client.py", line 1298, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1344, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1293, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1052, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 990, in send
    self.connect()
  File "/usr/lib/python3.11/http/client.py", line 1463, in connect
    super().connect()
  File "/usr/lib/python3.11/http/client.py", line 956, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

**Comment by R1kaB3rN** [comment]
> Traceback (most recent call last): File "/usr/share/ulwgl/ulwgl_run.py", line 330, in sys.exit(main()) ^^^^^^ File "/usr/share/ulwgl/ulwgl_run.py", line 309, in main check_env(env) File "/usr/share/ulwgl/ulwgl_run.py", line 151, in check_env get_ulwgl_proton(env) File "/usr/share/ulwgl/ulwgl_dl_util.py", line 24, in get_ulwgl_proton files = _fetch_releases() ^^^^^^^^^^^^^^^^^ File "/usr/share/ulwgl/ulwgl_dl_util.py", line 64, in _fetch_releases conn.request( File "/usr/lib/python3.11/http/client.py", line 1298, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/lib/python3.11/http/client.py", line 1344, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/lib/python3.11/http/client.py", line 1293, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/lib/python3.11/http/client.py", line 1052, in _send_output self.send(msg) File "/usr/lib/python3.11/http/client.py", line 990, in send self.connect() File "/usr/lib/python3.11/http/client.py", line 1463, in connect super().connect() File "/usr/lib/python3.11/http/client.py", line 956, in connect self.sock = self._create_connection( ^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/socket.py", line 827, in create_connection for res in getaddrinfo(host, port, 0, SOCK_STREAM): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ socket.gaierror: [Errno -3] Temporary failure in name resolution

Updated my branch again at https://github.com/Open-Wine-Components/ULWGL-launcher/pull/62.

If a FileNotFoundError is raised that's normal because we only look for ULWGL-Proton

**Comment by Aqa-Ib** [comment]
Now it works. Thank you very much !!!
