### ISSUE TITLE
nix flake

### ISSUE THREAD

**Issue by bohanubis** [Open-Wine-Components/ULWGL#71]
just here to ask if this project is willing to add nix flake just like neovim for exemple does here: https://github.com/neovim/neovim/tree/master/contrib

I will implement this if its allowed
and thanks

**Comment by loathingKernel** [comment]
I don't think anyone of the contributors so far is using NixOS and personally I don't even know what a nix flake is and what it's meant to provide. Is it a packaging specification?

If so I think it should have a place in this repo, as we already have  an rpm spec file, but you would have to contribute it unless someone else has experience with packaging for NixOS. Of course you will have to make sure it works and that it continues to work by adapting it as the project is still evolving.

**Comment by bohanubis** [comment]
ok gonna make a pull request soon thanks a lot

**Comment by bohanubis** [comment]
@loathingKernel just a quick question what are the architectures this projects support

**Comment by loathingKernel** [comment]
Currently, and for the foreseeable future, x86_64 only, due to Steam runtime.
