### ISSUE TITLE
Would it be possible to have the directory "Documents" points to somewhere else other than the directories inside the application environment (WINEPREFIX)?

### ISSUE THREAD

**Issue by ltsdw** [Open-Wine-Components/ULWGL#76]
I noticed that when I create a symbolic link "users/steamuser/Documents" (and I think every other directory) to point to somewhere else other than the directories inside the prefix, it will get "ignored" (in the sense that proton doesn't seem to be able to find the path the symlink points to, so it ignores it?).

Here's an example of what isn't working:

```
0 lrwxrwxrwx 1 med_user med_user 58 mar 29 00:47  Documents -> /storages/xfs_storage_partition/med_user/Desktop/Documents
0 lrwxrwxrwx 1 med_user med_user 11 mar 29 00:53 'My Documents' -> ./Documents
```

On my system XDG_DOCUMENTS_DIR points to /storages/xfs_storage_partition/med_user/Desktop/Documents, so different applications running through wine-ge/vanilla wine/etc have put their configuration files/addons/etc in there. And now applications running using umu/proton doesn't seem to find these configuration directories/files (and symlinking to the right directory doesn't seem work).

I may be wrong but I think this is somewhat of related to #63, as paths are expected to be relative to the application's prefix.

So while reading #15 I thought if it wouldn't be possible to make an exception for this case too?
If not, or if this is exactly the #63, please close this issue.

**Comment by loathingKernel** [comment]
From a first glance this is rather specific to your preferences, without much use elsewhere, so I'd be against. We need to keep the things in-scope. If you can provide examples or existing cases where it would be useful in general, it would help your case.

**Comment by ltsdw** [comment]
Not saying this should be the default behavior. Proton would still create a real directory under users/steamuser. But if someone wanted to, instead of having to copy their Documents from other prefixes or from their systems, they would simply create a symlink to elsewhere.

I think if a solution was to be found on #63, that would work here too (that's why I think this may be related to that one). Because I think it isn't about the symlink or anything else, is about the path the symlink points to is from somewhere else not relative to the WINEPREFIX.

But as I said it's totally okay to close this one if it's related to another issue or it's a "won't fix".

**Comment by GloriousEggroll** [comment]
I'm strongly against this. The 'My Documents' folder structure inside a wine prefix is specific to windows. Symlinking it elsewhere can easily lead to breakage. Many applications both store files within and rely on this structure (two examples being FFXIV and Warframe). Furthermore, the whole point of a prefix is that some games need changes that might break or otherwise affect other games. Performing those changes within a completely separate prefix per game prevents that. Those changes can be anywhere, which includes the 'My Documents' folder structure.

**Comment by ltsdw** [comment]
That's understandable, I think I can close this one now.
