### ISSUE TITLE
Does protonfixes gets applied no matter the PROTON_VERB used?

### ISSUE THREAD

**Issue by ltsdw** [Open-Wine-Components/ULWGL#79]
I don't know if this are just that the logs aren't being shown when using other PROTON_VERBs than waitforexitandrun, or protonfixes aren't being applied if not using waitforexitandrun.

Here it's Elder Scrolls Online run with PROTON_VERB `waitforexitandrun`:

```
ProtonFixes[1383968] INFO: Running protonfixes
ProtonFixes[1383968] INFO: Running checks
ProtonFixes[1383968] INFO: All checks successful
ProtonFixes[1383968] INFO: Non-steam game UNKNOWN (umu-306130)
ProtonFixes[1383968] INFO: Using global defaults for UNKNOWN (umu-306130)
ProtonFixes[1383968] INFO: Non-steam game UNKNOWN (umu-306130)
ProtonFixes[1383968] INFO: Using protonfix for UNKNOWN (umu-306130)
Proton: ARGV: waitforexitandrun
Proton: /home/med_user/.local/share/Games/TESO/pfx/drive_c/Program Files (x86)/Zenimax Online/The Elder Scrolls Online/game/client/eso64.exe
Proton: Executable a unix path, launching with /unix option.
wine: using kernel write watches, use_kernel_writewatch 1.
fsync: up and running.
wine: using kernel write watches, use_kernel_writewatch 1.
```

Here it's run with PROTON_VERB `runinprefix` (no mention of proton):

```
wine: using kernel write watches, use_kernel_writewatch 1.
fsync: up and running.
wine: using kernel write watches, use_kernel_writewatch 1.
```

Here it's run with PROTON_VERB `run`:
```
Proton: /home/med_user/.local/share/Games/TESO/pfx/drive_c/Program Files (x86)/Zenimax Online/The Elder Scrolls Online/game/client/eso64.exe
Proton: Executable a unix path, launching with /unix option.
wine: using kernel write watches, use_kernel_writewatch 1.
fsync: up and running.
```

I was told that what I'm experiencing might be related to an issue already fixed here: https://github.com/Open-Wine-Components/umu-protonfixes/commit/ac9ddf2660f4cd79ddc157424ee238926a4d6d30, but I'm not entirely sure as I tested with that fix and still experiencing the same behavior.

Is it supposed to be this way? Are the protonfixes being applied?

**Comment by R1kaB3rN** [comment]
That behavior you've observed is by design, though I wasn't the one who decided it. Protonfixes will only be applied if the `waitforprefixandrun` verb is specified, which is the default verb for the umu launcher.

And I think this is good to enforce for a controlled experience since some fixes can make a lot of big changes in the prefix which can be quite destructive for others and the current running game.

Therefore, my suggestion is to run games each in a separate prefix. And if you're worried about space, since the sum of each of your wine prefixes can be pretty large, you can create shallow copies of a clean prefix if you're on a CoW filesystem or deduplicate them for that problem. Though, I think umu can definitely automate that process for the user, assuming it's sane to do...

**Comment by ltsdw** [comment]
> That behavior you've observed is by design, though I wasn't the one who decided it. Protonfixes will only be applied if the waitforprefixandrun verb is specified, which is the default verb for the umu launcher.
> 
> And I think this is good to enforce for a controlled experience since some fixes can make a lot of big changes in the prefix which can be quite destructive for others and the current running game.


Oh that's great, actually I don't see a problem on this behavior, I just wanted to confirm it.

> Therefore, my suggestion is to run games each in a separate prefix.

Ah yes, actually I always run different applications on separate prefixes, there's only one application that requires me to run another program in the same prefix, but other than that I don't need to run different applications in same prefix.

> And if you're worried about space, since the sum of each of your wine prefixes can be pretty large, you can create shallow copies of a clean prefix if you're on a CoW filesystem or deduplicate them for that problem. 

Never considered that, though I don't use any CoW filesystem.

Thank you for clarifying this matter to me.

Closing.
