### ISSUE TITLE
how to use gamemode with this?

### ISSUE THREAD

**Issue by XxRiKxX** [Open-Wine-Components/ULWGL#81]
I tried with gamemoderun at the start of the command didnt worked. also tried it in between protonpath and the umu-run didnt worked either

**Comment by R1kaB3rN** [comment]
Personally, I do not use gamemode. However, when you mean it didn't work, are you referring to this error:

`ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

And assuming your command is in a similar form as: 

`WINEPREFIX= GAMEID= PROTONPATH= gamemoderun umu-run ~/foo.exe`

If so, there's currently an [open issue for this upstream](https://github.com/FeralInteractive/gamemode/issues/254). 

Also, at a glance, it's not even clear to me whether it's even compatibility with Proton or has even been applied correctly. While I can observe it's being applied to the launcher itself, game mode's shared library will not be brought into the runtime platform so I'm uncertain that it will even be applied to wine or the launched game.

**Comment by R1kaB3rN** [comment]
Closing as gamemode should be working correctly as long as you prepend gamemoderun before `umu-run`. You can verify this yourself with the command `gamemoded -s` while the launched game is running.

I have also confirmed that the relevant shared object libraries are correctly pulled within the runtime platform. For more details about this issue, please see https://github.com/FeralInteractive/gamemode/issues/345#issuecomment-1003372132.
