### ISSUE TITLE
Exception when launching any exe

### ISSUE THREAD

**Issue by mistermookiefun** [Open-Wine-Components/ULWGL#83]
Launching any exe gives me this:
ERROR:  Exception
Traceback (most recent call last):
  File "/usr/share/umu/umu_run.py", line 360, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/share/umu/umu_run.py", line 305, in main
    setup_umu(root, UMU_LOCAL)
  File "/usr/share/umu/umu_util.py", line 206, in setup_umu
    return _update_umu(root, local, STEAM_COMPAT, json, _get_json(local, CONFIG))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/umu/umu_util.py", line 444, in _get_json
    json = load(file)
           ^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by R1kaB3rN** [comment]
From the traceback, I can tell that you're running an outdated version of the launcher. Do you mind pulling from source and performing a clean install of the launcher?

But if you've acquired it from another source such as the AUR, then I recommend that you contact the maintainer to update it.

**Comment by mistermookiefun** [comment]
Hey! Thanks for the reply :D
Oh, well it is from the AUR.
I couldn't install it from sources, 
But from what I can see these are the commands?
git clone https://github.com/Open-Wine-Components/umu-launcher
cd umu-launcher
./configure.sh --prefix=/usr
make install
Is that it?

**Comment by mistermookiefun** [comment]
Oooh that's why I got it from the AUR, here's the traceback:
sudo make install
:: Building reaper
meson setup builddir/reaper subprojects/reaper

ERROR: Neither source directory 'builddir/reaper' nor build directory 'subprojects/reaper' contain a build file meson.build.
make: *** [Makefile.in:113: builddir/.build-reaper] Error 1

**Comment by R1kaB3rN** [comment]
> Hey! Thanks for the reply :D Oh, well it is from the AUR. I couldn't install it from sources, But from what I can see these are the commands? git clone https://github.com/Open-Wine-Components/umu-launcher cd umu-launcher ./configure.sh --prefix=/usr make install Is that it?

No problem. Well, if you're on Arch Linux, I'd actually recommend to just use your own PKGBUILD for now.

Here's an example taken from loathingkernel's PKGBUILD:
<pre>
pkgname=umu-launcher
pkgver=0.1.RC3.r373.2d44ca8
pkgrel=1
pkgdesc="This is the Unified Launcher for Windows Games on Linux, to run Proton with fixes outside of Steam"
arch=('x86_64')
url="https://github.com/Open-Wine-Components/umu-launcher"
license=('GPL-3.0-only')
depends=(
  # steam
  bash
  desktop-file-utils
  diffutils
  hicolor-icon-theme
  curl
  dbus
  freetype2
  gdk-pixbuf2
  ttf-font
  zenity
  lsb-release
  nss
  usbutils
  xorg-xrandr
  vulkan-driver
  vulkan-icd-loader
  lsof
  python
  xdg-user-dirs
  glibc
  libxcrypt
  libxcrypt-compat
  gcc-libs
)
depends_x86_64=(
  lib32-glibc
  lib32-libxcrypt
  lib32-libxcrypt-compat
  lib32-libgl
  lib32-gcc-libs
  lib32-libx11
  lib32-libxss
  lib32-alsa-plugins
  lib32-libgpg-error
  lib32-nss
  lib32-vulkan-driver
  lib32-vulkan-icd-loader
)
makedepends=(
  git
  meson
  ninja
  scdoc
)
provides=('ulwgl-launcher')
conflicts=('ulwgl-launcher')
replaces=('ulwgl-launcher')
install=
_commit=2d44ca8b45511a1732910a0cff8cd8f5fd7cf092
_origin="https://github.com/Open-Wine-Components/umu-launcher.git"
source=(
  "git+$_origin#commit=$_commit"
)
b2sums=("SKIP")

pkgver() {
  cd "$srcdir"/umu-launcher
  printf "%s" "$(git describe --long --tags | sed 's/\([^-]*-\)g/r\1/;s/-/./g')"
}

prepare() {
  cd "$srcdir"/umu-launcher
  git remote set-url origin "$_origin"
  git submodule update --init --filter=tree:0 --recursive
}

build() {
  cd "$srcdir/umu-launcher"
  ./configure.sh --prefix=/usr
  make
}

package() {
  cd "$srcdir/umu-launcher"
  make DESTDIR="$pkgdir" install
}
</pre>

Just note that you'll be responsible for maintaining it by updating the `_commit` variable or whatnot.

**Comment by R1kaB3rN** [comment]
> Oooh that's why I got it from the AUR, here's the traceback: sudo make install :: Building reaper meson setup builddir/reaper subprojects/reaper
> 
> ERROR: Neither source directory 'builddir/reaper' nor build directory 'subprojects/reaper' contain a build file meson.build. make: *** [Makefile.in:113: builddir/.build-reaper] Error 1

You were getting this error because the git submodules were not initialized which can be done via:  `git submodule update --init --filter=tree:0 --recursive`

Though, we shouldn't really let all users install with `make`. Once there's an official release, which should be sometime after Lutris's release, users would have the option to just use the prebuilt release and install it via their package manager.

But if you're using Lutris, you don't have to really worry about this because it will update it frequently.

**Comment by loathingKernel** [comment]
@R1kaB3rN you may ping me any time you consider a commit stable enough to be distributed. The AUR package is not abandoned but I cannot know what you consider WIP and what can be distributed until there are tagged releases.

**Comment by mistermookiefun** [comment]
@loathingKernel, you are the AUR maintainer?

**Comment by R1kaB3rN** [comment]
Closing because this isn't a bug that currently exists in the launcher.

**Comment by R1kaB3rN** [comment]
> @R1kaB3rN you may ping me any time you consider a commit stable enough to be distributed. The AUR package is not abandoned but I cannot know what you consider WIP and what can be distributed until there are tagged releases.

I'm not going to ping you every time to update it and tagged releases will need to be addressed later. For now, I think it's fine as long as it's in a recent commit where the CI passes
