### ISSUE TITLE
Exception when running umu-run without any argument

### ISSUE THREAD

**Issue by mistermookiefun** [Open-Wine-Components/ULWGL#84]
I launch this command: umu-run

OUTPUT:
usage: umu_run.py [-h] [--config CONFIG]

Unified Linux Wine Game Launcher

options:
  -h, --help       show this help message and exit
  --config CONFIG  path to TOML file (requires Python 3.11+)

See umu(1) for more info and examples.
**Traceback (most recent call last):
  File "/usr/share/umu/umu_run.py", line 360, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/share/umu/umu_run.py", line 291, in main
    args: Union[Namespace, Tuple[str, List[str]]] = parse_args()
                                                    ^^^^^^^^^^^^
  File "/usr/share/umu/umu_run.py", line 35, in parse_args
    raise SystemExit(err)
SystemExit: Please see project README.md for more info and examples.**
https://github.com/Open-Wine-Components/umu-launcher

During handling of the above exception, another exception occurred:

**Traceback (most recent call last):
  File "/usr/share/umu/umu_run.py", line 366, in <module>
    raise Exception(e)
Exception: Please see project README.md for more info and examples.
https://github.com/Open-Wine-Components/umu-launcher**

**Comment by R1kaB3rN** [comment]
Closing since this is intended and you must pass arguments when using this launcher. For usages, see umu(1).

Also, see https://github.com/Open-Wine-Components/umu-launcher/issues/83 for my other comment.
