### ISSUE TITLE
Can't get FSR working with umu Lutris

### ISSUE THREAD

**Issue by ShuraEx** [Open-Wine-Components/ULWGL#90]
Hello, I'm on Arch latest stock, I installed umu-launcher through the aur and have the latest lutris. GE-Proton(latest) appears in runners but if I launch the game(FFXIV) with it, the FSR resolution is no longer an option. on GE-Wine 8.26 it works fine, ingame I get the FSR resolution 1968x1107 but the not with GE-Proton(Latest). Because UMU uses proton and not wine, is the env needed to turn on FSR in lutris something else? Thanks for the help

**Comment by R1kaB3rN** [comment]
> Hello, I'm on Arch latest stock, I installed umu-launcher through the aur and have the latest lutris. GE-Proton(latest) appears in runners but if I launch the game(FFXIV) with it, the FSR resolution is no longer an option. on GE-Wine 8.26 it works fine, ingame I get the FSR resolution 1968x1107 but the not with GE-Proton(Latest). Because UMU uses proton and not wine, is the env needed to turn on FSR in lutris something else? Thanks for the help

umu uses UMU-Proton by default, which is basically stable Proton with protonfixes and I believe the FSR patch is not included in the build. To get FSR working, you'd either need to use gamescope or use a build that has the patch such as GE-Proton. To configure umu to use GE-Proton, you can simply add the environment variable `PROTONPATH=GE-Proton` in Lutris or set it when running the launcher.

**Comment by ShuraEx** [comment]
> > Hello, I'm on Arch latest stock, I installed umu-launcher through the aur and have the latest lutris. GE-Proton(latest) appears in runners but if I launch the game(FFXIV) with it, the FSR resolution is no longer an option. on GE-Wine 8.26 it works fine, ingame I get the FSR resolution 1968x1107 but the not with GE-Proton(Latest). Because UMU uses proton and not wine, is the env needed to turn on FSR in lutris something else? Thanks for the help
> 
> umu uses UMU-Proton by default, which is basically stable Proton with protonfixes and I believe the FSR patch is not included in the build. To get FSR working, you'd either need to use gamescope or use a build that has the patch such as GE-Proton. To configure umu to use GE-Proton, you can simply add the environment variable `PROTONPATH=GE-Proton` in Lutris or set it when running the launcher.

Thank You for the reply, didn't know UMU-Proton was a different build that didn't have the FSR patch. In Lutris it said GE-Proton(Latest) so thought it was using whatever the latest GE-Proton was. After installing GE-Proton 9.3, indeed the FSR resolution is selectable. Thank You so much for your help.
