### ISSUE TITLE
The prefix generation script is recursively creating symlinks to the "pfx" directory

### ISSUE THREAD

**Issue by Nemecyst** [Open-Wine-Components/ULWGL#93]
When creating a new prefix at the following path on my PC:
`/home/nemecyst/Games/GuildWars2/`

The symlink to the "pfx" folder is being recursively linked to itself. The end result is the following:
![image](https://github.com/Open-Wine-Components/umu-launcher/assets/9501781/ee01375e-1284-4b58-b4c6-2ba1a5790e36)

The path is the following with the last "pfx" being an empty file:
`/home/nemecyst/Games/GuildWars2/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx/pfx`

I'm using the latest Lutris on ArchLinux (https://archlinux.org/packages/extra/any/lutris/) and the runners that have this problem are GE-Proton (latest) and UMU-Proton-9.0-beta16-2.

I'm not a python dev but my gut feeling is that the error is around here: https://github.com/Open-Wine-Components/umu-launcher/blob/main/umu/umu_run.py#L93

**Comment by R1kaB3rN** [comment]
Thanks for filing a bug report. However, what you observed is not a bug in either Lutris or umu that should affect your ability to play a game, and the launcher does not recursively create a symbolic link infinitely. The launcher creates a symbolic link named `pfx` in the WINE prefix whose target is the parent directory, the WINE prefix itself, and this link will keep being re-created each launch in case the user moves their WINE prefix around. So in effect, when you follow the link, you'll just keep ending up in the same place and the file manager application, which looks to be Dolphin, will keep building the filesystem tree in that WINE prefix whenever you expand the `pfx` directory.

As for why the `pfx` directory is necessary, please see https://github.com/Open-Wine-Components/umu-launcher/pull/28#issuecomment-1943106293
